// SPDX-License-Identifier: GPL-3.0-or-later
// GENERATED by tools/i18n-extract.mjs from the catalogs in this directory.
// Do not edit by hand: run `npm run i18n:extract`.
//
// One entry per shipped catalog, so adding a translatewiki export is a data
// change rather than a code change. `qqq` is message documentation, not a
// locale, and is never listed here.
export const SHIPPED_LOCALES = ["en"];
