#!/usr/bin/env node
// SPDX-License-Identifier: GPL-3.0-or-later
// Generate docs/FEATURES.md from public_html/views/experiments.js.
// The experiments view is the product-facing source of truth; this script keeps
// the docs from becoming a stale second feature listing.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import * as espree from "espree";

const SOURCE = "public_html/views/experiments.js";
const OUTPUT = "docs/FEATURES.md";
const PARSE_OPTS = { ecmaVersion: 2023, sourceType: "module", loc: true };

function walkAst(node, visit) {
	if (!node || typeof node.type !== "string") return;
	visit(node);
	for (const key of Object.keys(node)) {
		if (key === "loc" || key === "range" || key === "parent") continue;
		const value = node[key];
		if (Array.isArray(value)) {
			for (const child of value) walkAst(child, visit);
		} else {
			walkAst(value, visit);
		}
	}
}

function propName(prop) {
	if (prop.key.type === "Identifier") return prop.key.name;
	if (prop.key.type === "Literal") return String(prop.key.value);
	return "";
}

function objectProps(node) {
	if (!node || node.type !== "ObjectExpression") return new Map();
	return new Map(
		node.properties.filter((prop) => prop.type === "Property").map((prop) => [propName(prop), prop.value])
	);
}

function textValue(node) {
	if (!node) return "";
	if (node.type === "Literal") return typeof node.value === "string" ? node.value : String(node.value);
	if (node.type === "TemplateLiteral" && node.expressions.length === 0) return node.quasis[0]?.value.cooked || "";
	if (node.type === "CallExpression" && node.callee.type === "Identifier" && node.callee.name === "t") {
		return textValue(node.arguments[1] || node.arguments[0]);
	}
	return "";
}

function requireText(props, key, label) {
	const value = textValue(props.get(key));
	if (!value) throw new Error(`${label} is missing ${key}`);
	return value;
}

function markdownText(value) {
	return value
		.replaceAll("—", "-")
		.replaceAll("–", "-")
		.replaceAll("…", "...")
		.replaceAll("“", '"')
		.replaceAll("”", '"')
		.replaceAll("’", "'")
		.replaceAll("|", "\\|")
		.replaceAll(/\s+/g, " ")
		.trim();
}

function featureGroupsFromExpression(node) {
	if (!node || node.type !== "ArrayExpression") throw new Error("EXPERIMENTS must be an array");
	return node.elements.map((groupNode, groupIndex) => {
		const groupProps = objectProps(groupNode);
		const group = requireText(groupProps, "group", `group ${groupIndex + 1}`);
		const itemsNode = groupProps.get("items");
		if (!itemsNode || itemsNode.type !== "ArrayExpression") {
			throw new Error(`group "${group}" is missing an items array`);
		}
		const items = itemsNode.elements.map((itemNode, itemIndex) => {
			const itemProps = objectProps(itemNode);
			const label = `feature ${itemIndex + 1} in "${group}"`;
			return {
				name: requireText(itemProps, "name", label),
				what: requireText(itemProps, "what", label),
				current: requireText(itemProps, "current", label),
				need: requireText(itemProps, "need", label),
				tryHref: textValue(itemProps.get("tryHref")),
				tryLabel: textValue(itemProps.get("tryLabel"))
			};
		});
		return { group, items };
	});
}

export function extractFeatureGroups(code) {
	const tree = espree.parse(code, PARSE_OPTS);
	let experiments = null;
	walkAst(tree, (node) => {
		if (node.type === "VariableDeclarator" && node.id.type === "Identifier" && node.id.name === "EXPERIMENTS") {
			experiments = node.init;
		}
	});
	if (!experiments) throw new Error("Could not find EXPERIMENTS in experiments.js");
	return featureGroupsFromExpression(experiments);
}

export function renderFeatureDocs(groups) {
	const total = groups.reduce((sum, group) => sum + group.items.length, 0);
	const rows = [];
	for (const group of groups) {
		for (const item of group.items) {
			const tryLink = item.tryHref ? `[${markdownText(item.tryLabel || "Try it")}](${item.tryHref})` : "-";
			rows.push([
				markdownText(group.group),
				markdownText(item.name),
				markdownText(item.what),
				markdownText(item.current),
				markdownText(item.need),
				tryLink
			]);
		}
	}
	const headers = ["Group", "Feature", "User value", "Current behavior", "Production need", "Try"];
	const widths = headers.map((header, index) => Math.max(3, header.length, ...rows.map((row) => row[index].length)));
	const tableRow = (cells) => `| ${cells.map((cell, index) => cell.padEnd(widths[index], " ")).join(" | ")} |`;
	const separator = `| ${widths.map((width) => "-".repeat(width)).join(" | ")} |`;
	return `<!-- SPDX-License-Identifier: GPL-3.0-or-later -->
<!-- Generated by \`npm run features:docs\`; do not edit by hand. -->

# Feature Listing

This document is generated from \`${SOURCE}\` (\`EXPERIMENTS\`), the product-facing
feature-status listing rendered at \`/experiments\`.

Run \`npm run features:docs\` after adding, removing, renaming, or changing a
feature. Pre-push and CI run \`npm run features:docs:check\` to block stale docs.

Total listed features: ${total}

${tableRow(headers)}
${separator}
${rows.map((row) => tableRow(row)).join("\n")}
`;
}

function main() {
	const generated = renderFeatureDocs(extractFeatureGroups(readFileSync(SOURCE, "utf8")));
	if (process.argv.includes("--check")) {
		const current = readFileSync(OUTPUT, "utf8");
		if (current !== generated) {
			console.error(`${OUTPUT} is stale. Run: npm run features:docs`);
			process.exit(1);
		}
		console.log("features: docs are up to date");
		return;
	}
	writeFileSync(OUTPUT, generated);
	console.log(`features: wrote ${OUTPUT}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
