#!/usr/bin/env node
// SPDX-License-Identifier: GPL-3.0-or-later
import { spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import * as espree from "espree";

const QUALITY_DIR = ".quality";
const REPORT_PATH = path.join(QUALITY_DIR, "report.json");
const CONTRACT_DIR = "tools/contracts";
const API_CONTRACT_PATH = path.join(CONTRACT_DIR, "public-api.json");
const MODULE_BUDGET_PATH = path.join(CONTRACT_DIR, "module-budgets.json");
const SOURCE_EXTS = new Set([".js", ".mjs", ".css", ".html", ".md", ".py", ".sh", ".json", ".svg"]);
const CODE_EXTS = new Set([".js", ".mjs", ".css", ".html", ".py", ".sh"]);
const JS_EXTS = new Set([".js", ".mjs"]);
const TEXT_LINE_LIMITS = new Map([
	[".js", 700],
	[".mjs", 700],
	[".py", 120],
	[".sh", 120],
	[".css", 640],
	[".html", 720]
]);
const FUNCTION_LIMITS = {
	lines: 240,
	branches: 36,
	nesting: 6,
	params: 8
};
const MODULE_DEFAULT_LIMITS = {
	lines: { ".js": 220, ".mjs": 220, ".css": 420, ".html": 720, ".py": 120, ".sh": 120 },
	branches: { ".js": 40, ".mjs": 40, ".py": 24, ".sh": 24 },
	fanIn: 8,
	fanOut: 8,
	importDepth: 6
};
const MUTATION_THRESHOLD = 95;
// ---- Gate 5: structural / semantic duplicates ----------------------------
const UI_SKELETON_PATH = path.join(CONTRACT_DIR, "ui-skeletons.json");
const DUP_FN_MIN_NODES = 18; // structural floor; skips getters / one-liners
const DUP_BRANCH_MIN_NODES = 8;
const DUP_UI_MIN_DEPTH = 3;
const DUP_UI_MIN_REPEAT = 3;
const DUP_CSS_MIN_DECLS = 4;
const DUP_CSS_MIN_GROUPS = 2;
const MAX_DIRECT_DEPENDENCY_RELEASE_AGE_DAYS = 548;
const DUPLICATE_WINDOW = 12;
const DESIGN_TOKEN_FILE = "public_html/styles/tokens.css";
const APP_ENTRY = "public_html/main.js";
const UPDATE_CONTRACTS = process.argv.includes("--update-contracts");
// Per-commit replay (pre-push, over the push range) runs only the pure-rule
// static gates: it skips mutation, the Playwright smoke run, and the snapshot
// contracts (which describe HEAD's final state, not every historical commit).
const REPLAY = process.argv.includes("--replay");
const GENERATED_PATTERNS = [
	/(^|\/)node_modules\//,
	/(^|\/)\.quality\//,
	/(^|\/)playwright-report\//,
	/(^|\/)test-results\//,
	/(^|\/)\.jscpd\//,
	/(^|\/)\.ruff_cache\//,
	/(^|\/)\.pytest_cache\//,
	/(^|\/)__pycache__\//,
	/(^|\/)\.eslintcache$/,
	/(^|\/)\.DS_Store$/,
	/\.pyc$/,
	/\.log$/,
	/\.orig$/,
	/\.rej$/,
	/\.bak$/
];
const FORBIDDEN_TEXT = [
	{ pattern: /\btodo\b/i, message: "TODO markers must be linked to an issue before landing" },
	{ pattern: /\bfixme\b/i, message: "FIXME markers must be linked to an issue before landing" },
	{ pattern: /\bxxx\b/i, message: "XXX markers are not allowed in committed code" },
	{ pattern: /\bhack\b/i, message: "HACK markers are not allowed in committed code" },
	{ pattern: /lorem ipsum/i, message: "placeholder lorem ipsum copy is not allowed" },
	{ pattern: /\bas an ai\b/i, message: "AI-disclosure filler text is not product copy" },
	{ pattern: /\bchatgpt\b/i, message: "AI tool residue must not be committed" },
	{ pattern: /\bcopilot\b/i, message: "AI tool residue must not be committed" },
	{ pattern: /generated by ai/i, message: "AI-generation residue must not be committed" }
];
const FORBIDDEN_CODE = [
	{ pattern: /\bdebugger\b/, message: "debugger statements are not allowed" },
	{
		pattern: /\bconsole\.(log|debug|trace|warn|error)\s*\(/,
		message: "console logging is not allowed in shipped code"
	},
	{ pattern: /\balert\s*\(/, message: "blocking alert() calls are not allowed; use inline UI state" }
];

// ---- Gate 8: architecture boundaries -------------------------------------
// The only modules allowed to reach the network / persistent storage. Keeping
// these confined is what lets the rest of the SPA stay a pure render layer.
const APPROVED_NETWORK = new Set(["public_html/lib/core/api.js"]);
const APPROVED_STORAGE = new Set([
	"public_html/lib/core/store.js",
	"public_html/lib/core/session.js",
	"public_html/lib/core/theme.js",
	"public_html/lib/core/i18n.js",
	"public_html/lib/core/signals.js"
]);
// Modules that must stay DOM-free (return HTML strings instead). dom.js owns the
// sanctioned query helpers; everything below core/atoms may render.
const RENDER_FORBIDDEN_PREFIXES = ["public_html/lib/core/", "public_html/lib/atoms/"];
const DOM_WRITE_ALLOW = new Set(["public_html/lib/core/dom.js", "public_html/lib/core/theme.js"]);
const FORBIDDEN_BROWSER_IMPORT = new Set([
	"fs",
	"path",
	"http",
	"https",
	"crypto",
	"child_process",
	"os",
	"url",
	"util",
	"stream"
]);
const FORBIDDEN_GLOBALS = [
	{ re: /\bprocess\.\w/, msg: "Node 'process' is not available in the browser" },
	{ re: /\brequire\s*\(/, msg: "CommonJS require() is not allowed; use ESM imports" },
	{ re: /\b__dirname\b|\b__filename\b/, msg: "Node module globals are not available in the browser" },
	{ re: /\beval\s*\(/, msg: "eval() is forbidden" },
	{ re: /\bdocument\.write\s*\(/, msg: "document.write() is forbidden" }
];
// Usage-shaped (not bare-word) so prose mentions of "localStorage"/"fetch" in
// comments or visible copy never trip the gate.
const STORAGE_RE =
	/\b(?:local|session)Storage\s*(?:\.\s*(?:get|set|remove|clear|key)|\[)|Object\.keys\(\s*localStorage|\bdocument\.cookie\b|\bindexedDB\b/;
const NETWORK_RE =
	/\bfetch\s*\(|\bXMLHttpRequest\b|\bnavigator\.sendBeacon\b|\bnew\s+WebSocket\b|\bnew\s+EventSource\b/;
// HTML injection + direct body manipulation. Core/atoms must be DOM-free; global
// state hooks like body.exp-off live in the app layer (main.js).
const DOM_MUTATE_RE =
	/\binnerHTML\s*=|\bouterHTML\s*=|\.insertAdjacentHTML\s*\(|document\.createElement|\.appendChild\s*\(|\.replaceChildren\s*\(|document\.body\./;

// ---- Gate 9: copy quality (UI strings only) ------------------------------
// Tunable word/phrase lists — keep tight to avoid flagging legitimate copy.
const COPY_FILLER = [
	"very",
	"really",
	"simply",
	"just simply",
	"basically",
	"at the end of the day",
	"needless to say"
];
const COPY_VAGUE_LABELS = new Set([
	"click here",
	"read more",
	"learn more",
	"click",
	"here",
	"info",
	"more",
	"this link",
	"submit"
]);
const COPY_PLACEHOLDER = ["lorem", "ipsum", "tbd", "tba", "foo", "bar", "baz", "coming soon", "placeholder text"];
const COPY_AI_PHRASES = [
	"delve",
	"seamless",
	"seamlessly",
	"robust",
	"elevate",
	"unlock the power",
	"in today's fast-paced",
	"it's worth noting",
	"game-changer",
	"tapestry",
	"testament to"
];
const COPY_LABEL_MAXLEN = 60;
// Mock data sources, not product copy.
const COPY_SCAN_EXCLUDE = new Set(["public_html/views/_fixtures.js", "tools/smoke-server.mjs"]);

// ---- Gate 10: git hygiene over the push range ----------------------------
const COMMIT_SUBJECT_MAX = 72;
const COMMIT_MAX_FILES = 40;
const COMMIT_MAX_DIFF_LINES = 800; // added + removed; tools/contracts/ snapshots exempt
const GIT_FALLBACK_COMMITS = 20;
const CONVENTIONAL_RE = /^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([\w./-]+\))?!?: .+/;
const IMPERATIVE_SUBJECT_RE = /^[A-Z]\S.*$/;
const IMPERATIVE_BAN_RE = /\b(wip|fixup|squash!|amend!|tmp|asdf|stuff|misc)\b/i;
const MERGE_NOISE_RE = /^Merge (branch|remote-tracking|pull request)\b/;
const CHURN_AREA_LIMIT = 3;

const root = repoRoot();
process.chdir(root);
mkdirSync(QUALITY_DIR, { recursive: true });

const failures = [];
const checks = [];
const startedAt = Date.now();
const files = gitFiles();

function repoRoot() {
	const out = spawnSync("git", ["rev-parse", "--show-toplevel"], { encoding: "utf8" });
	if (out.status !== 0) {
		console.error("quality: not inside a git checkout");
		process.exit(2);
	}
	return out.stdout.trim();
}

function gitFiles() {
	const out = spawnSync("git", ["ls-files", "--cached", "--others", "--exclude-standard", "-z"], {
		encoding: "utf8"
	});
	if (out.status !== 0) throw new Error(out.stderr || "git ls-files failed");
	return out.stdout
		.split("\0")
		.filter(Boolean)
		.filter((file) => existsSync(file) && statSync(file).isFile())
		.sort();
}

function fail(check, file, line, message) {
	failures.push({ check, file: file || null, line: line || null, message });
}

function read(file) {
	return readFileSync(file, "utf8");
}

function rel(file) {
	return file.split(path.sep).join("/");
}

function ext(file) {
	return path.extname(file);
}

function sourceFiles() {
	return files.filter((file) => SOURCE_EXTS.has(ext(file)));
}

function lineNumber(text, offset) {
	return text.slice(0, offset).split("\n").length;
}

function fileLineEntries(file, text) {
	return text.split(/\r?\n/).map((line, index) => ({ line, number: index + 1, file }));
}

function runCheck(name, fn) {
	const start = Date.now();
	const before = failures.length;
	try {
		fn(name);
	} catch (error) {
		fail(name, null, null, error && error.stack ? error.stack : String(error));
	}
	checks.push({ name, durationMs: Date.now() - start, failures: failures.length - before });
}

function command(check, cmd, args) {
	const out = spawnSync(cmd, args, { encoding: "utf8", cwd: root });
	if (out.status !== 0) {
		const output = [out.stdout, out.stderr].filter(Boolean).join("\n").trim();
		fail(check, args[args.length - 1], null, output || `${cmd} failed`);
	}
}

function commandWithEnv(cmd, args, env, opts = {}) {
	return spawnSync(cmd, args, {
		encoding: "utf8",
		cwd: root,
		env: { ...process.env, ...env },
		maxBuffer: opts.maxBuffer || 1024 * 1024,
		timeout: opts.timeout || 0
	});
}

function bin(name) {
	return path.join("node_modules", ".bin", name);
}

function pyBin(name) {
	return path.join(".quality", "python", "bin", name);
}

function requireFile(check, file, hint) {
	if (!existsSync(file)) fail(check, file, null, hint);
}

function stableJson(value) {
	return `${JSON.stringify(value, null, "\t")}\n`;
}

function formattedSnapshot(file, value) {
	const raw = stableJson(value);
	if (!existsSync(bin("prettier"))) return raw;
	const out = spawnSync(bin("prettier"), ["--stdin-filepath", file], {
		cwd: root,
		encoding: "utf8",
		input: raw
	});
	return out.status === 0 ? out.stdout : raw;
}

function readJson(file) {
	return JSON.parse(read(file));
}

function updateOrCompareSnapshot(check, file, actual, label) {
	const text = formattedSnapshot(file, actual);
	if (UPDATE_CONTRACTS) {
		mkdirSync(path.dirname(file), { recursive: true });
		writeFileSync(file, text);
		return;
	}
	if (!existsSync(file)) {
		fail(check, file, null, `${label} snapshot is missing; run npm run contracts:update`);
		return;
	}
	const expected = read(file);
	if (expected !== text) {
		fail(check, file, null, `${label} changed; review the diff and run npm run contracts:update if intentional`);
	}
}

runCheck("toolchain", (check) => {
	const major = Number(process.versions.node.split(".")[0]);
	if (major < 20) fail(check, null, null, `Node >= 20 is required; found ${process.version}`);
	if (spawnSync("git", ["--version"], { encoding: "utf8" }).status !== 0) fail(check, null, null, "git is required");
});

runCheck("repository hygiene", (check) => {
	for (const file of files) {
		const name = rel(file);
		for (const pattern of GENERATED_PATTERNS) {
			if (pattern.test(name)) {
				fail(check, file, null, "generated, cache, editor, or backup artifact is not allowed");
			}
		}
	}
	for (const required of ["public_html/index.html", "public_html/main.js", "proxy/app.py", "tools/deploy.sh"]) {
		if (!existsSync(required)) fail(check, required, null, "required project entrypoint is missing");
	}
});

runCheck("license headers", (check) => {
	for (const file of files) {
		const name = rel(file);
		if (!(/^(public_html|proxy|tools|tests)\//.test(name) && [".js", ".mjs", ".py", ".sh"].includes(ext(file)))) {
			continue;
		}
		const header = read(file).split(/\r?\n/).slice(0, 3).join("\n");
		if (!header.includes("SPDX-License-Identifier: GPL-3.0-or-later")) {
			fail(check, file, 1, "source files must declare the GPL-3.0-or-later SPDX header");
		}
	}
});

runCheck("syntax", (check) => {
	for (const file of files.filter((item) => JS_EXTS.has(ext(item)))) {
		command(check, process.execPath, ["--check", file]);
	}
	const pythonFiles = files.filter((item) => ext(item) === ".py");
	if (pythonFiles.length > 0) {
		const py = spawnSync("python3", ["--version"], { encoding: "utf8" });
		if (py.status === 0) for (const file of pythonFiles) command(check, "python3", ["-m", "py_compile", file]);
		else fail(check, null, null, "python3 is required for proxy syntax checks");
	}
	for (const file of files.filter((item) => ext(item) === ".json")) {
		try {
			JSON.parse(read(file));
		} catch (error) {
			fail(check, file, null, `invalid JSON: ${error.message}`);
		}
	}
});

// Node-tool gates share one shape: require the binary, then run it.
function binCheck(checkName, binName, args) {
	runCheck(checkName, (check) => {
		requireFile(check, bin(binName), "run npm ci before pushing");
		if (existsSync(bin(binName))) command(check, bin(binName), args);
	});
}

binCheck("prettier", "prettier", ["--check", "."]);
binCheck("eslint", "eslint", [".", "--max-warnings", "0"]);
binCheck("stylelint", "stylelint", ["public_html/styles/**/*.css"]);
binCheck("knip", "knip", ["--production"]);
binCheck("jscpd", "jscpd", ["--config", ".jscpd.json"]);

runCheck("npm audit", (check) => {
	if (REPLAY) return; // dependency audit is a HEAD-time check, not per-commit
	requireFile(check, "package-lock.json", "package-lock.json is required for npm audit");
	if (existsSync("package-lock.json")) command(check, "npm", ["audit", "--audit-level=moderate"]);
});

function directDependencies(pkg) {
	const sections = ["dependencies", "devDependencies", "optionalDependencies"];
	return sections
		.flatMap((section) => (pkg[section] ? Object.entries(pkg[section]) : []))
		.sort(([a], [b]) => a.localeCompare(b));
}

function npmViewJson(args) {
	const out = spawnSync("npm", ["view", ...args, "--json"], { encoding: "utf8", cwd: root });
	if (out.status !== 0) throw new Error([out.stdout, out.stderr].filter(Boolean).join("\n").trim());
	const text = out.stdout.trim();
	return text ? JSON.parse(text) : null;
}

runCheck("dependency policy", (check) => {
	const exactVersion = /^\d+\.\d+\.\d+(?:-[\d.A-Za-z-]+)?$/;
	requireFile(check, "package.json", "package.json is required");
	requireFile(check, "package-lock.json", "package-lock.json is required");
	if (!existsSync("package.json") || !existsSync("package-lock.json")) return;

	const pkg = readJson("package.json");
	const lock = readJson("package-lock.json");
	const rootPackage = lock.packages && lock.packages[""];
	if (!rootPackage) {
		fail(check, "package-lock.json", null, "lockfile root package metadata is missing");
		return;
	}

	for (const [name, version] of directDependencies(pkg)) {
		if (!exactVersion.test(version)) {
			fail(check, "package.json", null, `${name} must use an exact pinned version; found ${version}`);
		}
		const lockedSpec =
			(rootPackage.dependencies && rootPackage.dependencies[name]) ||
			(rootPackage.devDependencies && rootPackage.devDependencies[name]) ||
			(rootPackage.optionalDependencies && rootPackage.optionalDependencies[name]);
		if (lockedSpec !== version) {
			fail(
				check,
				"package-lock.json",
				null,
				`${name} lockfile spec ${lockedSpec || "<missing>"} must equal ${version}`
			);
		}
		const lockedPackage = lock.packages[`node_modules/${name}`];
		if (!lockedPackage || lockedPackage.version !== version) {
			fail(
				check,
				"package-lock.json",
				null,
				`${name} resolved version ${lockedPackage && lockedPackage.version ? lockedPackage.version : "<missing>"} must equal ${version}`
			);
		}
	}

	for (const [location, meta] of Object.entries(lock.packages || {})) {
		if (meta && meta.deprecated) {
			fail(check, "package-lock.json", null, `${location || "<root>"} is deprecated: ${meta.deprecated}`);
		}
	}

	for (const [name, version] of directDependencies(pkg)) {
		let deprecated;
		let time;
		try {
			deprecated = npmViewJson([`${name}@${version}`, "deprecated"]);
			time = npmViewJson([name, "time"]);
		} catch (error) {
			fail(check, "package.json", null, `could not read npm metadata for ${name}: ${error.message}`);
			continue;
		}
		if (deprecated) fail(check, "package.json", null, `${name}@${version} is deprecated: ${deprecated}`);
		const modifiedAt = time && time.modified ? Date.parse(time.modified) : Number.NaN;
		const versionPublishedAt = time && time[version] ? Date.parse(time[version]) : Number.NaN;
		if (!Number.isFinite(modifiedAt) || !Number.isFinite(versionPublishedAt)) {
			fail(check, "package.json", null, `${name} is missing registry release timestamps`);
			continue;
		}
		const ageDays = Math.floor((Date.now() - modifiedAt) / 86400000);
		if (ageDays > MAX_DIRECT_DEPENDENCY_RELEASE_AGE_DAYS) {
			fail(
				check,
				"package.json",
				null,
				`${name} has no release in ${ageDays} days; limit is ${MAX_DIRECT_DEPENDENCY_RELEASE_AGE_DAYS}`
			);
		}
	}
});

runCheck("ruff", (check) => {
	requireFile(check, pyBin("ruff"), "run tools/install-hooks.sh before pushing");
	if (existsSync(pyBin("ruff"))) {
		command(check, pyBin("ruff"), ["check", "proxy"]);
		command(check, pyBin("ruff"), ["format", "--check", "proxy"]);
	}
});

runCheck("pip audit", (check) => {
	if (REPLAY) return; // dependency audit is a HEAD-time check, not per-commit
	requireFile(check, pyBin("pip-audit"), "run tools/install-hooks.sh before pushing");
	if (existsSync(pyBin("pip-audit"))) {
		command(check, pyBin("pip-audit"), ["-r", "proxy/requirements.txt", "--strict"]);
	}
});

function unitTestFiles() {
	return files
		.filter((file) => rel(file).startsWith("tests/unit/") && file.endsWith(".test.mjs"))
		.map((file) => rel(file));
}

runCheck("unit tests", (check) => {
	const tests = unitTestFiles();
	if (tests.length === 0) {
		fail(check, "tests/unit", null, "unit tests are required for mutation testing");
		return;
	}
	command(check, process.execPath, ["--test", ...tests]);
});

runCheck("playwright axe smoke", (check) => {
	if (REPLAY) return; // HEAD-only: too slow to replay per commit
	requireFile(check, bin("playwright"), "run npm ci and npx playwright install chromium before pushing");
	if (existsSync(bin("playwright"))) command(check, bin("playwright"), ["test"]);
});

runCheck("text hygiene", (check) => {
	for (const file of sourceFiles()) {
		const name = rel(file);
		const scanForbiddenText = name !== "tools/quality.mjs";
		const scanForbiddenCode = name.startsWith("public_html/") && CODE_EXTS.has(ext(file));
		const text = read(file);
		for (const entry of fileLineEntries(file, text)) {
			if (/^(<<<<<<<|=======|>>>>>>>)($| )/.test(entry.line)) {
				fail(check, file, entry.number, "merge conflict marker is not allowed");
			}
			if (scanForbiddenText) {
				for (const rule of FORBIDDEN_TEXT) {
					if (rule.pattern.test(entry.line)) fail(check, file, entry.number, rule.message);
				}
			}
			if (scanForbiddenCode) {
				for (const rule of FORBIDDEN_CODE) {
					if (rule.pattern.test(entry.line)) fail(check, file, entry.number, rule.message);
				}
			}
			const limit = TEXT_LINE_LIMITS.get(ext(file));
			if (limit && entry.line.length > limit) {
				fail(check, file, entry.number, `line is ${entry.line.length} chars; limit is ${limit}`);
			}
		}
	}
});

// Collapse a raw HTML/template fragment to its visible label text: drop nested
// tags and ${...} interpolations, unescape nothing, trim and collapse whitespace.
function labelText(fragment) {
	return fragment
		.replaceAll(/\${[^}]*}/g, "")
		.replaceAll(/<[^>]*>/g, "")
		.replaceAll(/\s+/g, " ")
		.trim();
}

// Visible text runs (between > and <) with line numbers, for an HTML file or for
// the template-literal spans of a JS file. Static <script>/<style> bodies and
// ${...} interpolations are excluded so only user-facing copy is scanned.
function copyRuns(file) {
	const text = read(file);
	const runs = [];
	const isHtml = ext(file) === ".html";
	const haystacks = [];
	if (isHtml) {
		const stripped = text.replaceAll(/<script\b[\S\s]*?<\/script>|<style\b[\S\s]*?<\/style>/gi, (m) =>
			" ".repeat(m.length)
		);
		haystacks.push({ body: stripped, base: 0 });
	} else {
		for (const m of text.matchAll(/`([^\\`]*(?:\\.[^\\`]*)*)`/g)) {
			if (!m[1].includes("<")) continue;
			haystacks.push({ body: m[1], base: m.index + 1 });
		}
	}
	for (const { body, base } of haystacks) {
		for (const m of body.matchAll(/>([^<]+)</g)) {
			const raw = m[1];
			const visible = raw
				.replaceAll(/\${[^}]*}/g, "")
				.replaceAll(/\s+/g, " ")
				.trim();
			if (visible) runs.push({ text: visible, line: lineNumber(text, base + m.index + 1) });
		}
	}
	return runs;
}

function copyLabels(file) {
	const text = read(file);
	const labels = [];
	for (const m of text.matchAll(/<(a|button|h1|h2|h3)\b[^>]*>([\S\s]*?)<\/\1>/gi)) {
		const label = labelText(m[2]);
		if (!label) continue;
		// "Simple" = a real label, not a card/container: no text-bearing nested
		// element once icons are removed (link cards with title+desc are skipped).
		const simple = !/<[A-Za-z]/.test(m[2].replaceAll(/<svg\b[\S\s]*?<\/svg>/gi, ""));
		labels.push({ tag: m[1].toLowerCase(), text: label, line: lineNumber(text, m.index), simple });
	}
	return labels;
}

runCheck("copy quality", (check) => {
	const copyFiles = files.filter(
		(item) =>
			!COPY_SCAN_EXCLUDE.has(rel(item)) &&
			(rel(item) === "public_html/index.html" || (rel(item).startsWith("public_html/") && JS_EXTS.has(ext(item))))
	);
	for (const file of copyFiles) {
		const headingSeen = new Map(); // duplicate headings are scoped per page/file
		for (const run of copyRuns(file)) {
			const lower = run.text.toLowerCase();
			for (const word of COPY_FILLER) {
				if (new RegExp(`\\b${word.replaceAll(/[$()*+.?[\\\]^{|}]/g, "\\$&")}\\b`).test(lower)) {
					fail(check, file, run.line, `filler word "${word}" — tighten the copy`);
				}
			}
			for (const word of COPY_PLACEHOLDER) {
				if (new RegExp(`\\b${word}\\b`).test(lower)) {
					fail(check, file, run.line, `placeholder copy "${word}" must be replaced`);
				}
			}
			for (const phrase of COPY_AI_PHRASES) {
				if (lower.includes(phrase)) {
					fail(check, file, run.line, `AI-cliché phrasing "${phrase}" — rewrite in plain product voice`);
				}
			}
		}
		for (const label of copyLabels(file)) {
			if (label.simple && COPY_VAGUE_LABELS.has(label.text.toLowerCase())) {
				fail(
					check,
					file,
					label.line,
					`vague ${label.tag} label "${label.text}" — describe the destination/action`
				);
			}
			if (label.simple && label.text.length > COPY_LABEL_MAXLEN) {
				fail(
					check,
					file,
					label.line,
					`${label.tag} label is ${label.text.length} chars; keep UI labels under ${COPY_LABEL_MAXLEN}`
				);
			}
			if (["h1", "h2", "h3"].includes(label.tag)) {
				const key = label.text.toLowerCase();
				const prev = headingSeen.get(key);
				if (prev) {
					fail(
						check,
						file,
						label.line,
						`duplicate heading "${label.text}" (first at ${prev.file}:${prev.line})`
					);
				} else {
					headingSeen.set(key, { file: rel(file), line: label.line });
				}
			}
		}
	}
});

function importsFor(file) {
	const text = read(file);
	const imports = [];
	const regex = /(?:^|\n)(\s*import\s+([\S\s]*?)\s+from\s+["']([^"']+)["'];)/g;
	let match;
	while ((match = regex.exec(text))) {
		const index = match.index + (match[0].startsWith("\n") ? 1 : 0);
		imports.push({ spec: match[3], index, line: lineNumber(text, index) });
	}
	return imports;
}

function resolveImport(file, spec) {
	return rel(path.normalize(path.join(path.dirname(file), spec)));
}

function layerOf(file) {
	const name = rel(file);
	if (name === "public_html/main.js") return { layer: 5, label: "app" };
	if (name.startsWith("public_html/views/")) return { layer: 4, label: "views" };
	if (name.startsWith("public_html/lib/organisms/")) return { layer: 3, label: "organisms" };
	if (name.startsWith("public_html/lib/molecules/")) return { layer: 2, label: "molecules" };
	if (name.startsWith("public_html/lib/atoms/")) return { layer: 1, label: "atoms" };
	if (name.startsWith("public_html/lib/core/")) return { layer: 0, label: "core" };
	return { layer: -1, label: "other" };
}

function importAllowed(source, target) {
	const s = layerOf(source);
	const t = layerOf(target);
	if (s.layer === -1 || t.layer === -1) return true;
	if (source === "public_html/main.js") return true;
	if (source === "public_html/views/router.js" && target.startsWith("public_html/views/")) return true;
	return t.layer <= s.layer;
}

runCheck("imports and architecture", (check) => {
	const graph = new Map();
	const browserFiles = files.filter((item) => JS_EXTS.has(ext(item)) && rel(item).startsWith("public_html/"));
	for (const file of browserFiles) {
		const seen = new Set();
		const deps = [];
		for (const item of importsFor(file)) {
			if (seen.has(item.spec)) fail(check, file, item.line, `duplicate import from ${item.spec}`);
			seen.add(item.spec);
			if (!item.spec.startsWith(".")) {
				fail(check, file, item.line, `browser modules must use local relative imports; found ${item.spec}`);
				continue;
			}
			if (!item.spec.endsWith(".js")) {
				fail(check, file, item.line, `local imports must include the .js extension: ${item.spec}`);
			}
			const target = resolveImport(file, item.spec);
			if (!existsSync(target)) {
				fail(check, file, item.line, `import target does not exist: ${item.spec}`);
				continue;
			}
			if (target === rel(file)) fail(check, file, item.line, "self-import is not allowed");
			if (!importAllowed(rel(file), target)) {
				fail(
					check,
					file,
					item.line,
					`${layerOf(file).label} layer must not import upward from ${layerOf(target).label}`
				);
			}
			deps.push(target);
		}
		graph.set(rel(file), deps);
	}
	const visiting = new Set();
	const visited = new Set();
	const stack = [];
	function dfs(node) {
		if (visiting.has(node)) {
			fail(
				check,
				node,
				null,
				`circular import detected: ${[...stack.slice(stack.indexOf(node)), node].join(" -> ")}`
			);
			return;
		}
		if (visited.has(node)) return;
		visiting.add(node);
		stack.push(node);
		for (const dep of graph.get(node) || []) dfs(dep);
		stack.pop();
		visiting.delete(node);
		visited.add(node);
	}
	for (const node of graph.keys()) dfs(node);
});

runCheck("architecture boundaries", (check) => {
	const browserFiles = files.filter((item) => JS_EXTS.has(ext(item)) && rel(item).startsWith("public_html/"));
	for (const file of browserFiles) {
		const name = rel(file);
		const text = read(file);
		// Forbidden imports: browser modules must never pull in Node built-ins.
		for (const item of importsFor(file)) {
			const spec = item.spec.replace(/^node:/, "");
			if (item.spec.startsWith("node:") || FORBIDDEN_BROWSER_IMPORT.has(spec)) {
				fail(check, file, item.line, `browser module must not import Node built-in "${item.spec}"`);
			}
		}
		const entries = fileLineEntries(file, text);
		for (const entry of entries) {
			for (const rule of FORBIDDEN_GLOBALS) {
				if (rule.re.test(entry.line)) fail(check, file, entry.number, rule.msg);
			}
			if (!APPROVED_NETWORK.has(name) && NETWORK_RE.test(entry.line)) {
				fail(
					check,
					file,
					entry.number,
					"network access is only allowed in lib/core/api.js; route this through apiGet()"
				);
			}
			if (!APPROVED_STORAGE.has(name) && STORAGE_RE.test(entry.line)) {
				fail(
					check,
					file,
					entry.number,
					"persistent storage is only allowed in core (store/session/theme/i18n/signals); move it to lib/core/store.js"
				);
			}
			if (
				RENDER_FORBIDDEN_PREFIXES.some((prefix) => name.startsWith(prefix)) &&
				!DOM_WRITE_ALLOW.has(name) &&
				DOM_MUTATE_RE.test(entry.line)
			) {
				fail(
					check,
					file,
					entry.number,
					"core/atoms modules must be DOM-free; return HTML strings and let a molecule/organism/view render"
				);
			}
		}
	}
});

function exportedNames(file) {
	const text = read(file);
	const names = new Set();
	for (const match of text.matchAll(/export\s+(?:async\s+)?function\s+([$A-Z_a-z][\w$]*)/g)) names.add(match[1]);
	for (const match of text.matchAll(/export\s+(?:const|let|var)\s+([$A-Z_a-z][\w$]*)/g)) names.add(match[1]);
	for (const match of text.matchAll(/export\s*{\s*([^}]+)\s*}/g)) {
		for (const raw of match[1].split(",")) {
			const exported = raw
				.trim()
				.split(/\s+as\s+/)
				.pop()
				.trim();
			if (exported) names.add(exported);
		}
	}
	return [...names].sort();
}

function matchingBraceEnd(text, start) {
	let depth = 0;
	let quote = "";
	let lineComment = false;
	let blockComment = false;
	let escaped = false;
	for (let index = start; index < text.length; index += 1) {
		const char = text[index];
		const next = text[index + 1];
		if (lineComment) {
			if (char === "\n") lineComment = false;
			continue;
		}
		if (blockComment) {
			if (char === "*" && next === "/") {
				blockComment = false;
				index += 1;
			}
			continue;
		}
		if (quote) {
			if (escaped) {
				escaped = false;
			} else if (char === "\\") {
				escaped = true;
			} else if (char === quote) {
				quote = "";
			}
			continue;
		}
		if (char === "/" && next === "/") {
			lineComment = true;
			index += 1;
			continue;
		}
		if (char === "/" && next === "*") {
			blockComment = true;
			index += 1;
			continue;
		}
		if (char === '"' || char === "'" || char === "`") {
			quote = char;
			continue;
		}
		if (char === "{") {
			depth += 1;
		} else if (char === "}") {
			depth -= 1;
			if (depth === 0) return index;
		}
	}
	return -1;
}

function extractObjectBody(text, marker) {
	const markerIndex = text.indexOf(marker);
	if (markerIndex === -1) return "";
	const start = text.indexOf("{", markerIndex);
	if (start === -1) return "";
	const end = matchingBraceEnd(text, start);
	return end === -1 ? "" : text.slice(start + 1, end);
}

function quotedKeyAt(body, index, quoteChar) {
	let end = index + 1;
	while (end < body.length) {
		if (body[end] === "\\" && end + 1 < body.length) {
			end += 2;
			continue;
		}
		if (body[end] === quoteChar) break;
		end += 1;
	}
	if (end >= body.length) return null;
	return { key: body.slice(index + 1, end), index: end };
}

function identifierKeyAt(body, index) {
	const match = /^[$A-Z_a-z][\w$-]*/.exec(body.slice(index));
	return match ? { key: match[0], index: index + match[0].length - 1 } : null;
}

function objectKeyAt(body, index) {
	const char = body[index];
	if (char === '"' || char === "'") return quotedKeyAt(body, index, char);
	return /[$A-Z_a-z]/.test(char) ? identifierKeyAt(body, index) : null;
}

function hasColonAfterKey(body, index) {
	let probe = index + 1;
	while (/\s/.test(body[probe] || "")) probe += 1;
	return body[probe] === ":";
}

function topLevelObjectKeys(body) {
	const keys = [];
	let depth = 0;
	let quote = "";
	let escaped = false;
	for (let index = 0; index < body.length; index += 1) {
		const char = body[index];
		if (quote) {
			if (escaped) escaped = false;
			else if (char === "\\") escaped = true;
			else if (char === quote) quote = "";
			continue;
		}

		if (depth === 0) {
			const candidate = objectKeyAt(body, index);
			if (candidate && hasColonAfterKey(body, candidate.index)) {
				keys.push(candidate.key);
				index = candidate.index;
				continue;
			}
		}

		if (char === '"' || char === "'" || char === "`") {
			quote = char;
			continue;
		}
		if (char === "{" || char === "(" || char === "[") depth += 1;
		else if (char === "}" || char === ")" || char === "]") depth = Math.max(0, depth - 1);
	}
	return [...new Set(keys)].sort();
}

function objectKeysFromConst(file, name) {
	const text = read(file);
	return [
		...topLevelObjectKeys(extractObjectBody(text, `const ${name} =`)),
		...topLevelObjectKeys(extractObjectBody(text, `export const ${name} =`))
	];
}

function publicRoutes() {
	const routeKeys = objectKeysFromConst("public_html/views/router.js", "ROUTES").map((key) => `/${key}`);
	const staticKeys = objectKeysFromConst("public_html/views/static.js", "STATIC").map((key) => `/${key}`);
	const patterns = [
		"/",
		"/search",
		"/by/:name",
		"/tools/create",
		"/tools/:name",
		"/tools/:name/edit",
		"/tools/:name/edit-annotations",
		"/tools/:name/history",
		"/tools/:name/history/:revision",
		"/lists/create",
		"/lists/:id",
		"/lists/:id/edit",
		"/lists/:id/history"
	];
	return [...new Set([...patterns, ...routeKeys, ...staticKeys])].sort();
}

function schemaShapes() {
	const apiText = read("public_html/lib/core/api.js");
	const normalizedTool = [
		...topLevelObjectKeys(extractObjectBody(apiText, "const o =")),
		"status",
		"weeklyViews"
	].sort();
	const normalizedList = topLevelObjectKeys(extractObjectBody(apiText, "return"));
	return {
		normalizeList: normalizedList,
		normalizeTool: [...new Set(normalizedTool)].sort()
	};
}

function publicApiContract() {
	const exports = {};
	for (const file of files.filter((item) => JS_EXTS.has(ext(item)) && rel(item).startsWith("public_html/"))) {
		const names = exportedNames(file);
		if (names.length > 0) exports[rel(file)] = names;
	}
	return {
		exports,
		routes: publicRoutes(),
		schemas: schemaShapes()
	};
}

runCheck("public API contract", (check) => {
	if (REPLAY) return; // snapshot describes HEAD, not historical commits
	updateOrCompareSnapshot(check, API_CONTRACT_PATH, publicApiContract(), "public API contract");
});

runCheck("links and route safety", (check) => {
	for (const file of files.filter((item) => [".js", ".html"].includes(ext(item)))) {
		const text = read(file);
		for (const entry of fileLineEntries(file, text)) {
			if (entry.line.includes("/#/")) fail(check, file, entry.number, "hash-router URLs are not allowed");
			if (/href=["']#["']/.test(entry.line)) {
				fail(check, file, entry.number, 'dead href="#" links are not allowed');
			}
			if (/href=["'][^"']+\.html["#'?]/.test(entry.line)) {
				fail(check, file, entry.number, "local links must use app routes, not .html files");
			}
		}
		for (const match of text.matchAll(/<a\b[\S\s]*?>/g)) {
			const tag = match[0];
			if (!/\btarget\s*=\s*["']_blank["']/.test(tag) || tag.includes("EXTERNAL_REL")) continue;
			const rel = tag.match(/\brel\s*=\s*(["'])(.*?)\1/);
			const relTokens = new Set((rel ? rel[2] : "").split(/\s+/).filter(Boolean));
			if (!relTokens.has("noopener") || !relTokens.has("nofollow")) {
				fail(
					check,
					file,
					lineNumber(text, match.index),
					'target="_blank" must include rel="noopener nofollow"'
				);
			}
		}
		for (const tag of text.match(/<img\b[^>]*>/g) || []) {
			if (!/\balt=/.test(tag)) {
				fail(check, file, lineNumber(text, text.indexOf(tag)), "img tags must include alt text");
			}
		}
	}
});

function cssWithoutComments(file) {
	return read(file).replaceAll(/\/\*[\S\s]*?\*\//g, "");
}

function designTokens() {
	const tokens = new Set();
	const colorValues = new Set();
	if (!existsSync(DESIGN_TOKEN_FILE)) return { tokens, colorValues };
	const text = cssWithoutComments(DESIGN_TOKEN_FILE);
	const definitionRegex = /(--[\w-]+)\s*:\s*([^;]+);/g;
	let match;
	while ((match = definitionRegex.exec(text))) {
		tokens.add(match[1]);
		for (const color of match[2].match(/#[\dA-Fa-f]{3,8}\b/g) || []) colorValues.add(color.toLowerCase());
	}
	return { tokens, colorValues };
}

function styleLinkOrder() {
	const html = read("public_html/index.html");
	return [...html.matchAll(/<link\b[^>]*href=["']([^"']+\.css)["'][^>]*>/g)].map((match) =>
		match[1].replace(/^\.\//, "")
	);
}

runCheck("design system drift", (check) => {
	const { tokens, colorValues } = designTokens();
	if (tokens.size === 0) fail(check, DESIGN_TOKEN_FILE, null, "design token source is missing or empty");
	const cssOrder = styleLinkOrder();
	if (cssOrder[0] !== "/styles/tokens.css") {
		fail(check, "public_html/index.html", null, "tokens.css must be the first stylesheet loaded");
	}
	for (const required of [
		"--color-surface",
		"--color-text",
		"--space-4",
		"--fs-body",
		"--radius-sm",
		"--focus-ring"
	]) {
		if (!tokens.has(required)) {
			fail(check, DESIGN_TOKEN_FILE, null, `required design token is missing: ${required}`);
		}
	}
	for (const file of files.filter(
		(item) => [".css", ".js", ".html"].includes(ext(item)) && rel(item).startsWith("public_html/")
	)) {
		const name = rel(file);
		const text = ext(file) === ".css" ? cssWithoutComments(file) : read(file);
		let match;
		const varRegex = /var\(\s*(--[\w-]+)/g;
		while ((match = varRegex.exec(text))) {
			const token = match[1];
			if (!tokens.has(token)) fail(check, file, lineNumber(text, match.index), `unknown design token ${token}`);
		}
		const definitionRegex = /(^|[\s;{])(--[\w-]+)\s*:/g;
		while ((match = definitionRegex.exec(text))) {
			const token = match[2];
			if (name !== DESIGN_TOKEN_FILE && !tokens.has(token)) {
				fail(
					check,
					file,
					lineNumber(text, match.index),
					`custom property ${token} must be registered in ${DESIGN_TOKEN_FILE}`
				);
			}
		}
		const colorRegex = /#[\dA-Fa-f]{3,8}\b|rgba?\([^)]+\)|hsla?\([^)]+\)/g;
		while ((match = colorRegex.exec(text))) {
			const literal = match[0].toLowerCase();
			if (name === DESIGN_TOKEN_FILE) continue;
			let message = null;
			if (ext(file) === ".css") message = `raw colour ${literal} must be a design token`;
			else if (!colorValues.has(literal)) message = `raw colour ${literal} is not registered in design tokens`;
			if (message) fail(check, file, lineNumber(text, match.index), message);
		}
	}
});

function splitSelectors(raw) {
	const selectors = [];
	let current = "";
	let depth = 0;
	let quote = "";
	for (const char of raw) {
		if (quote) {
			current += char;
			if (char === quote) quote = "";
			continue;
		}
		if (char === '"' || char === "'") {
			quote = char;
			current += char;
			continue;
		}
		if (char === "(" || char === "[") depth += 1;
		else if (char === ")" || char === "]") depth = Math.max(0, depth - 1);
		if (char === "," && depth === 0) {
			selectors.push(current.trim());
			current = "";
		} else {
			current += char;
		}
	}
	if (current.trim()) selectors.push(current.trim());
	return selectors;
}

runCheck("CSS selectors", (check) => {
	for (const file of files.filter((item) => ext(item) === ".css")) {
		const text = cssWithoutComments(file);
		const seen = new Map();
		const regex = /([^{}]+){([^{}]*)}/g;
		let match;
		while ((match = regex.exec(text))) {
			const raw = match[1].trim();
			if (!raw || raw.startsWith("@") || raw === "from" || raw === "to" || raw.endsWith("%")) continue;
			const body = match[2].trim().replaceAll(/\s+/g, " ");
			if (!body) continue;
			for (const selector of splitSelectors(raw).filter(Boolean)) {
				const key = `${selector} { ${body} }`;
				const first = seen.get(key);
				const line = lineNumber(text, match.index);
				if (first) {
					fail(check, file, line, `duplicate selector/body "${selector}" first appeared on line ${first}`);
				} else {
					seen.set(key, line);
				}
			}
		}
	}
});

function escapeRegex(value) {
	return value.replaceAll(/[$()*+.?[\\\]^{|}]/g, "\\$&");
}

function identifierOccurrences(text, name) {
	return [...text.matchAll(new RegExp(`(?<![A-Za-z0-9_$])${escapeRegex(name)}(?![A-Za-z0-9_$])`, "g"))].length;
}

function browserModuleGraph() {
	const browserFiles = files
		.filter((item) => JS_EXTS.has(ext(item)) && rel(item).startsWith("public_html/"))
		.map((file) => rel(file));
	const graph = new Map(browserFiles.map((file) => [file, []]));
	for (const file of browserFiles) {
		for (const item of importsFor(file)) {
			if (!item.spec.startsWith(".")) continue;
			const target = resolveImport(file, item.spec);
			if (graph.has(target)) graph.get(file).push(target);
		}
	}
	return graph;
}

function jsModuleGraph() {
	const moduleFiles = files.filter((item) => JS_EXTS.has(ext(item))).map((file) => rel(file));
	const graph = new Map(moduleFiles.map((file) => [file, []]));
	for (const file of moduleFiles) {
		for (const item of importsFor(file)) {
			if (!item.spec.startsWith(".")) continue;
			const target = resolveImport(file, item.spec);
			if (graph.has(target)) graph.get(file).push(target);
		}
	}
	return graph;
}

function importDepthFor(file, graph, seen = new Set()) {
	if (seen.has(file)) return 0;
	const deps = graph.get(file) || [];
	if (deps.length === 0) return graph.has(file) ? 1 : 0;
	const nextSeen = new Set(seen);
	nextSeen.add(file);
	return 1 + Math.max(...deps.map((dep) => importDepthFor(dep, graph, nextSeen)));
}

function codeModuleFiles() {
	return files.filter((file) => CODE_EXTS.has(ext(file))).map((file) => rel(file));
}

function moduleCyclomatic(text) {
	return 1 + (text.match(/\b(if|for|while|case|catch)\b|\?|&&|\|\|/g) || []).length;
}

function moduleCognitive(text) {
	let score = 0;
	let nesting = 0;
	for (const line of text.split(/\r?\n/)) {
		const trimmed = line.trim();
		if (/^[)\]}]/.test(trimmed)) nesting = Math.max(0, nesting - 1);
		const controls = trimmed.match(/\b(if|for|while|case|catch|switch)\b|\?|&&|\|\|/g) || [];
		score += controls.length * (1 + nesting);
		const opens = (trimmed.match(/[([{]/g) || []).length;
		const closes = (trimmed.match(/[)\]}]/g) || []).length;
		nesting = Math.max(0, nesting + opens - closes);
	}
	return score;
}

function moduleMetrics() {
	const graph = jsModuleGraph();
	const fanIn = new Map([...graph.keys()].map((file) => [file, 0]));
	for (const deps of graph.values()) {
		for (const dep of deps) fanIn.set(dep, (fanIn.get(dep) || 0) + 1);
	}
	const modules = {};
	for (const file of codeModuleFiles()) {
		const text = read(file);
		modules[file] = {
			lines: text.split(/\r?\n/).length,
			cyclomatic: moduleCyclomatic(text),
			cognitive: moduleCognitive(text),
			fanIn: fanIn.get(file) || 0,
			fanOut: (graph.get(file) || []).length,
			importDepth: importDepthFor(file, graph)
		};
	}
	return { defaults: MODULE_DEFAULT_LIMITS, modules };
}

function defaultModuleBudget(file) {
	const extension = ext(file);
	return {
		lines: MODULE_DEFAULT_LIMITS.lines[extension] || 120,
		cyclomatic: MODULE_DEFAULT_LIMITS.branches[extension] || 20,
		cognitive: (MODULE_DEFAULT_LIMITS.branches[extension] || 20) * 2,
		fanIn: MODULE_DEFAULT_LIMITS.fanIn,
		fanOut: MODULE_DEFAULT_LIMITS.fanOut,
		importDepth: MODULE_DEFAULT_LIMITS.importDepth
	};
}

runCheck("module complexity budgets", (check) => {
	if (REPLAY) return; // snapshot describes HEAD, not historical commits
	const actual = moduleMetrics();
	if (UPDATE_CONTRACTS) {
		updateOrCompareSnapshot(check, MODULE_BUDGET_PATH, actual, "module budgets");
		return;
	}
	if (!existsSync(MODULE_BUDGET_PATH)) {
		fail(check, MODULE_BUDGET_PATH, null, "module budget snapshot is missing; run npm run contracts:update");
		return;
	}
	const expected = readJson(MODULE_BUDGET_PATH);
	for (const file of Object.keys(expected.modules || {})) {
		if (!actual.modules[file]) {
			fail(check, MODULE_BUDGET_PATH, null, `${file} was deleted; update module budget snapshot`);
		}
	}
	for (const [file, metrics] of Object.entries(actual.modules)) {
		const budget = (expected.modules && expected.modules[file]) || defaultModuleBudget(file);
		for (const [metric, value] of Object.entries(metrics)) {
			if (value > budget[metric]) {
				fail(check, file, null, `${metric} is ${value}; budget is ${budget[metric]}`);
			}
		}
	}
});

function reachableModules(graph, entry) {
	const seen = new Set();
	function visit(node) {
		if (seen.has(node) || !graph.has(node)) return;
		seen.add(node);
		for (const dep of graph.get(node)) visit(dep);
	}
	visit(entry);
	return seen;
}

function classNamesInSource() {
	const names = new Set();
	for (const file of files.filter(
		(item) => [".js", ".html"].includes(ext(item)) && rel(item).startsWith("public_html/")
	)) {
		for (const match of read(file).matchAll(/[A-Za-z][\w-]*(?:__[A-Za-z][\w-]*)?(?:--[A-Za-z][\w-]*)?/g)) {
			names.add(match[0]);
		}
	}
	return names;
}

runCheck("dead code", (check) => {
	const graph = browserModuleGraph();
	const reachable = reachableModules(graph, APP_ENTRY);
	for (const file of graph.keys()) {
		if (!reachable.has(file)) fail(check, file, null, "browser module is not reachable from public_html/main.js");
	}
	const referencedClasses = classNamesInSource();
	for (const file of files.filter((item) => ext(item) === ".css" && rel(item).startsWith("public_html/styles/"))) {
		const text = cssWithoutComments(file);
		for (const match of text.matchAll(/\.([A-Za-z][\w-]*)/g)) {
			const name = match[1];
			if (name.startsWith("is-") || name.startsWith("has-") || name.startsWith("on-")) continue;
			if (!referencedClasses.has(name)) {
				fail(
					check,
					file,
					lineNumber(text, match.index),
					`CSS class .${name} is not referenced outside stylesheets`
				);
			}
		}
	}
	for (const file of files.filter((item) => JS_EXTS.has(ext(item)) && rel(item).startsWith("public_html/"))) {
		const text = read(file);
		for (const match of text.matchAll(/export\s+function\s+([$A-Z_a-z][\w$]*)/g)) {
			const name = match[1];
			if (identifierOccurrences(text, name) === 1) {
				let imported = false;
				for (const other of files.filter((item) => JS_EXTS.has(ext(item)) && item !== file)) {
					if (read(other).includes(name)) {
						imported = true;
						break;
					}
				}
				if (!imported) {
					fail(check, file, lineNumber(text, match.index), `exported function ${name} appears unused`);
				}
			}
		}
	}
});

function normalizeDuplicateLine(line) {
	return line
		.trim()
		.replaceAll(/(["'`])(?:\\.|(?!\1).)*\1/g, '""')
		.replaceAll(/\b\d+(?:\.\d+)?\b/g, "0")
		.replaceAll(/\s+/g, " ");
}

runCheck("duplicate blocks", (check) => {
	const seen = new Map();
	for (const file of files.filter((item) => [".js", ".mjs", ".css", ".html"].includes(ext(item)))) {
		const normalized = read(file)
			.split(/\r?\n/)
			.map((line) => normalizeDuplicateLine(line));
		for (let index = 0; index <= normalized.length - DUPLICATE_WINDOW; index += 1) {
			const window = normalized.slice(index, index + DUPLICATE_WINDOW);
			if (window.some((line) => !line || line === "}" || line === "};" || line.startsWith("import "))) continue;
			if (window.join("").length < 240) continue;
			const key = window.join("\n");
			const previous = seen.get(key);
			if (previous && (previous.file !== file || previous.line !== index + 1)) {
				fail(
					check,
					file,
					index + 1,
					`duplicate ${DUPLICATE_WINDOW}-line block first appeared in ${previous.file}:${previous.line}`
				);
			} else {
				seen.set(key, { file, line: index + 1 });
			}
		}
	}
});

function functionRanges(text) {
	const ranges = [];
	const regex = /function\s+([$A-Z_a-z][\w$]*)\s*\(([^)]*)\)\s*{/g;
	let match;
	while ((match = regex.exec(text))) {
		const open = text.indexOf("{", match.index);
		const close = matchingBraceEnd(text, open);
		const end = close === -1 ? match.index : close + 1;
		ranges.push({ name: match[1], params: match[2], start: match.index, end });
	}
	return ranges;
}

runCheck("code shape budgets", (check) => {
	for (const file of files.filter((item) => JS_EXTS.has(ext(item)))) {
		const text = read(file);
		for (const fn of functionRanges(text)) {
			const body = text.slice(fn.start, fn.end);
			const lines = body.split(/\r?\n/).length;
			const branches = (body.match(/\b(if|for|while|case|catch|\?|&&|\|\|)\b/g) || []).length;
			const params = fn.params
				.split(",")
				.map((item) => item.trim())
				.filter(Boolean).length;
			if (lines > FUNCTION_LIMITS.lines) {
				fail(check, file, lineNumber(text, fn.start), `${fn.name} has ${lines} lines`);
			}
			if (branches > FUNCTION_LIMITS.branches) {
				fail(check, file, lineNumber(text, fn.start), `${fn.name} has ${branches} branches`);
			}
			if (params > FUNCTION_LIMITS.params) {
				fail(check, file, lineNumber(text, fn.start), `${fn.name} has ${params} parameters`);
			}
		}
	}
});

function normalizeFunctionBody(lines) {
	return lines
		.map((line) => normalizeDuplicateLine(line))
		.filter((line) => line && line !== "}" && line !== "};")
		.join("\n")
		.replaceAll(/\b[$A-Z_a-z][\w$]*\b/g, (word) =>
			[
				"if",
				"else",
				"for",
				"while",
				"return",
				"const",
				"let",
				"var",
				"function",
				"await",
				"async",
				"new"
			].includes(word)
				? word
				: "id"
		);
}

runCheck("duplicate functions", (check) => {
	const seen = new Map();
	for (const file of files.filter((item) => JS_EXTS.has(ext(item)))) {
		const text = read(file);
		for (const fn of functionRanges(text)) {
			const body = normalizeFunctionBody(text.slice(fn.start, fn.end).split(/\r?\n/));
			if (body.length < 240) continue;
			const previous = seen.get(body);
			if (previous) {
				fail(
					check,
					file,
					lineNumber(text, fn.start),
					`${fn.name} duplicates ${previous.file}:${previous.line}`
				);
			} else {
				seen.set(body, { file, line: lineNumber(text, fn.start) });
			}
		}
	}
});

const ESPREE_OPTS = { ecmaVersion: 2023, sourceType: "module", loc: true };
const astCache = new Map();
function parseJs(file) {
	if (astCache.has(file)) return astCache.get(file);
	let tree = null;
	try {
		tree = espree.parse(read(file), ESPREE_OPTS);
	} catch {
		tree = null; // the `syntax` gate (node --check) owns parse errors
	}
	astCache.set(file, tree);
	return tree;
}
function astChildren(node) {
	const kids = [];
	for (const key of Object.keys(node)) {
		if (key === "loc" || key === "range" || key === "start" || key === "end") continue;
		const value = node[key];
		if (Array.isArray(value)) {
			for (const child of value) if (child && typeof child.type === "string") kids.push(child);
		} else if (value && typeof value.type === "string") {
			kids.push(value);
		}
	}
	return kids;
}
function walkAst(node, visit) {
	if (!node || typeof node.type !== "string") return;
	visit(node);
	for (const child of astChildren(node)) walkAst(child, visit);
}
// Structural fingerprint of a subtree. Literals are anonymized but identifiers are
// kept verbatim (so Math.max- and Math.min-shaped code do NOT collide) — trading
// rename-clone recall for precision, which is the right call under strict mode.
const NAMED_NODE_LABEL = { Identifier: "Id", PrivateIdentifier: "Pvt" };
function structuralKey(node) {
	let label = node.type;
	if (node.type === "Literal" || node.type === "TemplateElement") label = "Lit";
	else if (NAMED_NODE_LABEL[node.type]) label = `${NAMED_NODE_LABEL[node.type]}:${node.name}`;
	const kids = astChildren(node).map((child) => structuralKey(child));
	let count = 1;
	for (const kid of kids) count += kid.count;
	return { key: `${label}(${kids.map((kid) => kid.key).join(",")})`, count };
}

runCheck("structural duplicates", (check) => {
	// 5a/5b — AST duplicate functions and near-duplicate sibling branches across all
	// JS (app, tooling, and tests).
	const fnSeen = new Map();
	for (const file of files.filter((item) => JS_EXTS.has(ext(item)))) {
		const tree = parseJs(file);
		if (!tree) continue;
		const handledChain = new Set();
		walkAst(tree, (node) => {
			if (
				node.type === "FunctionDeclaration" ||
				node.type === "FunctionExpression" ||
				node.type === "ArrowFunctionExpression"
			) {
				const sk = structuralKey(node.body);
				if (sk.count < DUP_FN_MIN_NODES) return;
				const here = { file: rel(file), line: node.loc.start.line };
				const prev = fnSeen.get(sk.key);
				if (prev) {
					fail(
						check,
						file,
						here.line,
						`function body structurally duplicates ${prev.file}:${prev.line} (${sk.count} nodes)`
					);
				} else {
					fnSeen.set(sk.key, here);
				}
			}
			if (node.type === "IfStatement" && !handledChain.has(node)) {
				const blocks = [];
				let cur = node;
				while (cur && cur.type === "IfStatement") {
					handledChain.add(cur);
					blocks.push(cur.consequent);
					cur = cur.alternate;
				}
				if (cur) blocks.push(cur);
				flagSiblingDuplicates(check, file, blocks);
			}
			if (node.type === "SwitchStatement") {
				flagSiblingDuplicates(
					check,
					file,
					node.cases.map((c) => ({ loc: c.loc, type: "BlockStatement", body: c.consequent }))
				);
			}
		});
	}

	// 5c — repeated UI structures in index.html (review-gated snapshot, because the
	// footer's four nav columns are an intentional repeat). JS template HTML is out
	// of scope here (covered by the regex clone gates).
	const indexFile = files.find((item) => rel(item) === "public_html/index.html");
	if (indexFile && !REPLAY) {
		const counts = new Map();
		for (const sig of htmlSkeletons(read(indexFile))) counts.set(sig, (counts.get(sig) || 0) + 1);
		const catalog = [...counts.entries()]
			.filter(([, n]) => n >= DUP_UI_MIN_REPEAT)
			.map(([signature, occurrences]) => ({ signature, occurrences }))
			.sort((a, b) => a.signature.localeCompare(b.signature));
		updateOrCompareSnapshot(check, UI_SKELETON_PATH, catalog, "repeated UI structures");
	}

	// 5d — repeated CSS declaration sets shared across distinct selectors.
	for (const file of files.filter((item) => ext(item) === ".css")) {
		const text = cssWithoutComments(file);
		const declSeen = new Map();
		const regex = /([^{}]+){([^{}]*)}/g;
		let match;
		while ((match = regex.exec(text))) {
			const raw = match[1].trim();
			if (!raw || raw.startsWith("@") || raw === "from" || raw === "to" || raw.endsWith("%")) continue;
			const decls = match[2]
				.split(";")
				.map((d) => d.trim().replaceAll(/\s+/g, " "))
				.filter(Boolean)
				.sort();
			if (decls.length < DUP_CSS_MIN_DECLS) continue;
			const key = decls.join("; ");
			const line = lineNumber(text, match.index);
			const selectors = splitSelectors(raw).filter(Boolean).join(", ");
			const prev = declSeen.get(key);
			if (prev && prev.selectors !== selectors) {
				prev.group.add(selectors);
				if (prev.group.size >= DUP_CSS_MIN_GROUPS) {
					fail(
						check,
						file,
						line,
						`${decls.length} identical declarations shared with "${prev.selectors}" (line ${prev.line}); extract a shared class or :where() group`
					);
				}
			} else if (!prev) {
				declSeen.set(key, { selectors, line, group: new Set([selectors]) });
			}
		}
	}
});

function flagSiblingDuplicates(check, file, blocks) {
	const seen = new Map();
	for (const block of blocks) {
		if (!block || typeof block.type !== "string") continue;
		const sk = structuralKey(block);
		if (sk.count < DUP_BRANCH_MIN_NODES) continue;
		const line = block.loc.start.line;
		const prev = seen.get(sk.key);
		if (prev) {
			fail(
				check,
				file,
				line,
				`branch body duplicates the sibling branch at line ${prev}; collapse or table-drive it`
			);
		} else {
			seen.set(sk.key, line);
		}
	}
}

function htmlSkeletons(text) {
	const TAG = /<(\/?)([A-Za-z][\w-]*)((?:[^"'>]|"[^"]*"|'[^']*')*?)(\/?)>/g;
	const VOID = new Set([
		"area",
		"base",
		"br",
		"col",
		"embed",
		"hr",
		"img",
		"input",
		"link",
		"meta",
		"param",
		"source",
		"track",
		"wbr"
	]);
	const roots = [];
	const stack = [];
	let match;
	while ((match = TAG.exec(text))) {
		const closing = match[1] === "/";
		const tag = match[2].toLowerCase();
		if (closing) {
			for (let i = stack.length - 1; i >= 0; i -= 1) {
				if (stack[i].tag === tag) {
					stack.length = i;
					break;
				}
			}
			continue;
		}
		const classMatch = /class\s*=\s*"([^"]*)"/.exec(match[3]);
		const classes = classMatch ? classMatch[1].trim().split(/\s+/).filter(Boolean).sort() : [];
		const node = { tag, classes, children: [] };
		if (stack.length > 0) stack[stack.length - 1].children.push(node);
		else roots.push(node);
		if (!(match[4] === "/" || VOID.has(tag))) stack.push(node);
	}
	const signatures = [];
	function signatureOf(node) {
		const self = node.classes.length > 0 ? `${node.tag}.${node.classes.join(".")}` : node.tag;
		const kids = node.children.map((child) => signatureOf(child));
		const depth = kids.length > 0 ? 1 + Math.max(...kids.map((kid) => kid.depth)) : 1;
		const sig = kids.length > 0 ? `${self}[${kids.map((kid) => kid.sig).join(",")}]` : self;
		if (depth >= DUP_UI_MIN_DEPTH && node.classes.length > 0) signatures.push(sig);
		return { sig, depth };
	}
	for (const node of roots) signatureOf(node);
	return signatures;
}

const MUTATION_TARGETS = new Map([
	["public_html/lib/core/api.js", ["firstUrl", "hasValue", "normalizeList", "normalizeTool", "pick", "statusOf"]],
	["public_html/lib/core/dom.js", ["dirAttrs", "esc", "hash", "normalizeVcsUrl", "safeUrl"]],
	["public_html/lib/core/routing.js", ["authorHref", "listHref", "toolHref"]],
	["public_html/lib/core/signals.js", ["completeness", "endorsementOf", "fitsContext", "freshness", "wikiMatches"]],
	[
		"public_html/lib/core/similarity.js",
		["cosine", "idf", "nearestNeighbors", "normalizeVector", "termsOf", "vectorFor"]
	],
	["public_html/lib/core/synth.js", ["synthHealth", "synthSeed", "synthThanks", "synthUsage", "synthViews"]],
	["public_html/lib/core/util.js", ["memoizeAsync", "normStr"]]
]);

const MUTATORS = [
	{ name: "strict equality", pattern: /===/g, replacement: "!==" },
	{ name: "strict inequality", pattern: /!==/g, replacement: "===" },
	{ name: "less-or-equal", pattern: /(?<=\s)<=(?=\s)/g, replacement: "<" },
	{ name: "greater-or-equal", pattern: /(?<=\s)>=(?=\s)/g, replacement: ">" },
	{ name: "less-than", pattern: /(?<=\s)<(?=\s)/g, replacement: "<=" },
	{ name: "greater-than", pattern: /(?<=\s)>(?=\s)/g, replacement: ">=" },
	{ name: "logical and", pattern: /&&/g, replacement: "||" },
	{ name: "logical or", pattern: /\|\|/g, replacement: "&&" },
	{ name: "true literal", pattern: /\btrue\b/g, replacement: "false" },
	{ name: "false literal", pattern: /\bfalse\b/g, replacement: "true" },
	{ name: "math max", pattern: /\bMath\.max\b/g, replacement: "Math.min" },
	{ name: "math min", pattern: /\bMath\.min\b/g, replacement: "Math.max" },
	{ name: "empty string return", pattern: /return ""/g, replacement: "return null" },
	{ name: "null return", pattern: /return null/g, replacement: 'return ""' }
];

function mutationCandidates() {
	const candidates = [];
	for (const [file, names] of MUTATION_TARGETS) {
		if (!existsSync(file)) {
			candidates.push({ missing: true, file, name: "<file>", line: null });
			continue;
		}
		const text = read(file);
		const ranges = functionRanges(text).filter((range) => names.includes(range.name));
		const found = new Set(ranges.map((range) => range.name));
		for (const name of names) {
			if (!found.has(name)) candidates.push({ missing: true, file, name, line: null });
		}
		for (const range of ranges) {
			const body = text.slice(range.start, range.end);
			for (const mutator of MUTATORS) {
				let match;
				while ((match = mutator.pattern.exec(body))) {
					const index = range.start + match.index;
					const candidate = {
						file,
						functionName: range.name,
						line: lineNumber(text, index),
						mutator: mutator.name,
						index,
						from: match[0],
						to: mutator.replacement
					};
					if (!isEquivalentMutation(text, candidate)) candidates.push(candidate);
				}
			}
		}
	}
	return candidates;
}

function isEquivalentMutation(text, mutant) {
	const line = text.split(/\r?\n/)[mutant.line - 1] || "";
	if (
		mutant.file === "public_html/lib/core/dom.js" &&
		mutant.functionName === "safeUrl" &&
		mutant.mutator === "logical or" &&
		line.includes("u === null || u === undefined")
	) {
		return true;
	}
	if (
		mutant.file === "public_html/lib/core/similarity.js" &&
		mutant.functionName === "vectorFor" &&
		mutant.mutator === "logical or" &&
		line.includes("FACET_WEIGHTS[facet] || 1")
	) {
		return true;
	}
	if (
		mutant.file === "public_html/lib/core/similarity.js" &&
		mutant.functionName === "cosine" &&
		mutant.mutator === "less-or-equal" &&
		line.includes("vecA.size <= vecB.size")
	) {
		return true;
	}
	return false;
}

function applyMutation(text, mutant) {
	return text.slice(0, mutant.index) + mutant.to + text.slice(mutant.index + mutant.from.length);
}

function runUnitTestsAgainst(rootDir) {
	return commandWithEnv(
		process.execPath,
		["--max-old-space-size=256", "--test", ...unitTestFiles()],
		{ TOOLHUB_CORE_ROOT: path.resolve(rootDir) },
		{ timeout: 8000 }
	);
}

function runMutant(mutant) {
	const tempRoot = mkdtempSync(path.join(QUALITY_DIR, "mutation-"));
	try {
		cpSync("public_html", path.join(tempRoot, "public_html"), { recursive: true });
		const target = path.join(tempRoot, mutant.file);
		writeFileSync(target, applyMutation(read(mutant.file), mutant));
		const out = runUnitTestsAgainst(tempRoot);
		return {
			killed: out.status !== 0,
			stdout: out.stdout,
			stderr: out.stderr
		};
	} finally {
		rmSync(tempRoot, { recursive: true, force: true });
	}
}

runCheck("mutation testing", (check) => {
	if (REPLAY) return; // HEAD-only: too slow to replay per commit
	const tests = unitTestFiles();
	if (tests.length === 0) {
		fail(check, "tests/unit", null, "unit tests are required before mutation testing");
		return;
	}
	const baseline = runUnitTestsAgainst(root);
	if (baseline.status !== 0) {
		fail(check, "tests/unit", null, [baseline.stdout, baseline.stderr].filter(Boolean).join("\n").trim());
		return;
	}

	const candidates = mutationCandidates();
	const missing = candidates.filter((candidate) => candidate.missing);
	for (const candidate of missing) {
		fail(check, candidate.file, candidate.line, `mutation target ${candidate.name} was not found`);
	}
	const mutants = candidates.filter((candidate) => !candidate.missing);
	if (mutants.length === 0) {
		fail(check, null, null, "no mutation candidates were generated");
		return;
	}

	const survivors = [];
	let killed = 0;
	for (const mutant of mutants) {
		const result = runMutant(mutant);
		if (result.killed) {
			killed += 1;
		} else {
			survivors.push(mutant);
		}
	}
	const score = (killed / mutants.length) * 100;
	writeFileSync(
		path.join(QUALITY_DIR, "mutation-report.json"),
		stableJson({
			threshold: MUTATION_THRESHOLD,
			score: Number(score.toFixed(2)),
			killed,
			total: mutants.length,
			survivors
		})
	);
	if (score < MUTATION_THRESHOLD) {
		fail(
			check,
			path.join(QUALITY_DIR, "mutation-report.json"),
			null,
			`mutation score ${score.toFixed(2)}% is below ${MUTATION_THRESHOLD}% (${survivors.length} survived)`
		);
		for (const survivor of survivors.slice(0, 10)) {
			fail(
				check,
				survivor.file,
				survivor.line,
				`survived mutant in ${survivor.functionName}: ${survivor.mutator} (${survivor.from} -> ${survivor.to})`
			);
		}
	}
});

function gitOut(args) {
	const out = spawnSync("git", args, { encoding: "utf8", cwd: root });
	return out.status === 0 ? out.stdout : "";
}

function pushRangeCommits() {
	const base = gitOut(["merge-base", "origin/main", "HEAD"]).trim();
	if (base) {
		// Known upstream: check exactly what is ahead of it (empty when in sync).
		const list = gitOut(["rev-list", `${base}..HEAD`]).trim();
		return list ? list.split("\n").filter(Boolean) : [];
	}
	// No upstream to diff against (e.g. fresh clone) — degrade to recent commits.
	return gitOut(["rev-list", "--max-count", String(GIT_FALLBACK_COMMITS), "HEAD"])
		.trim()
		.split("\n")
		.filter(Boolean);
}

function areaOf(file) {
	const top = file.split("/")[0];
	return top === "public_html" || top === "proxy" || top === "tools" || top === "tests" ? top : "root";
}

runCheck("git hygiene", (check) => {
	if (REPLAY) return; // range check is a HEAD-time gate, not a per-commit one
	for (const sha of pushRangeCommits()) {
		const short = sha.slice(0, 9);
		const subject = (gitOut(["show", "-s", "--format=%s", sha]).split("\n")[0] || "").trim();
		if (!subject) continue;
		if (MERGE_NOISE_RE.test(subject)) {
			fail(check, null, null, `commit ${short}: merge commits should not be in the push range; rebase instead`);
			continue;
		}
		if (!CONVENTIONAL_RE.test(subject) && !IMPERATIVE_SUBJECT_RE.test(subject)) {
			fail(
				check,
				null,
				null,
				`commit ${short}: subject must be Conventional Commits or a capitalized imperative ("${subject}")`
			);
		}
		if (IMPERATIVE_BAN_RE.test(subject)) {
			fail(check, null, null, `commit ${short}: WIP/fixup/tmp commits must be squashed before pushing`);
		}
		if (subject.length > COMMIT_SUBJECT_MAX) {
			fail(
				check,
				null,
				null,
				`commit ${short}: subject is ${subject.length} chars; keep it under ${COMMIT_SUBJECT_MAX}`
			);
		}
		if (subject.endsWith(".")) {
			fail(check, null, null, `commit ${short}: subject must not end with a period`);
		}
		const numstat = gitOut(["diff-tree", "--no-commit-id", "--numstat", "-r", sha]).trim();
		const rows = numstat ? numstat.split("\n").filter(Boolean) : [];
		const paths = [];
		let changed = 0;
		let snapshotOnly = true;
		for (const row of rows) {
			const [added, removed, file] = row.split("\t");
			if (!file) continue;
			paths.push(file);
			if (!file.startsWith("tools/contracts/")) {
				changed += (Number(added) || 0) + (Number(removed) || 0);
				snapshotOnly = false;
			}
			if (GENERATED_PATTERNS.some((re) => re.test(file))) {
				fail(check, file, null, `commit ${short} adds a generated artifact (${file})`);
			}
		}
		if (paths.length > COMMIT_MAX_FILES) {
			fail(
				check,
				null,
				null,
				`commit ${short} touches ${paths.length} files; split it (limit ${COMMIT_MAX_FILES})`
			);
		}
		if (!snapshotOnly && changed > COMMIT_MAX_DIFF_LINES) {
			fail(
				check,
				null,
				null,
				`commit ${short} changes ${changed} lines; split it (limit ${COMMIT_MAX_DIFF_LINES})`
			);
		}
		const areas = new Set(paths.map((file) => areaOf(file)));
		if (areas.size >= CHURN_AREA_LIMIT) {
			fail(
				check,
				null,
				null,
				`commit ${short} spans unrelated areas (${[...areas].sort().join(", ")}); keep commits focused`
			);
		}
	}
});

const report = {
	startedAt: new Date(startedAt).toISOString(),
	durationMs: Date.now() - startedAt,
	checks,
	failures
};
writeFileSync(REPORT_PATH, `${JSON.stringify(report, null, 2)}\n`);

if (failures.length > 0) {
	console.error(`quality: failed ${failures.length} deterministic gate${failures.length === 1 ? "" : "s"}`);
	for (const failure of failures) {
		const location = [failure.file, failure.line].filter(Boolean).join(":");
		console.error(`- [${failure.check}] ${location} ${failure.message}`);
	}
	console.error(`Full report: ${REPORT_PATH}`);
	process.exit(1);
}

console.log(`quality: ${checks.length} checks passed in ${Date.now() - startedAt}ms`);
