#!/usr/bin/env node
// SPDX-License-Identifier: GPL-3.0-or-later
import { spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const QUALITY_DIR = ".quality";
const REPORT_PATH = path.join(QUALITY_DIR, "report.json");
const CONTRACT_DIR = "tools/contracts";
const API_CONTRACT_PATH = path.join(CONTRACT_DIR, "public-api.json");
const MODULE_BUDGET_PATH = path.join(CONTRACT_DIR, "module-budgets.json");
const SOURCE_EXTS = new Set([".js", ".mjs", ".css", ".html", ".md", ".py", ".sh", ".json", ".svg"]);
const CODE_EXTS = new Set([".js", ".mjs", ".css", ".html", ".py", ".sh"]);
const JS_EXTS = new Set([".js", ".mjs"]);
const TEXT_LINE_LIMITS = new Map([
	[".js", 700],
	[".mjs", 700],
	[".py", 120],
	[".sh", 120],
	[".css", 640],
	[".html", 720]
]);
const FUNCTION_LIMITS = {
	lines: 240,
	branches: 36,
	nesting: 6,
	params: 8
};
const MODULE_DEFAULT_LIMITS = {
	lines: { ".js": 220, ".mjs": 220, ".css": 420, ".html": 720, ".py": 120, ".sh": 120 },
	branches: { ".js": 40, ".mjs": 40, ".py": 24, ".sh": 24 },
	fanIn: 8,
	fanOut: 8,
	importDepth: 6
};
const MUTATION_THRESHOLD = 95;
const MAX_DIRECT_DEPENDENCY_RELEASE_AGE_DAYS = 548;
const DUPLICATE_WINDOW = 12;
const DESIGN_TOKEN_FILE = "public_html/styles/tokens.css";
const APP_ENTRY = "public_html/main.js";
const UPDATE_CONTRACTS = process.argv.includes("--update-contracts");
const GENERATED_PATTERNS = [
	/(^|\/)node_modules\//,
	/(^|\/)\.quality\//,
	/(^|\/)playwright-report\//,
	/(^|\/)test-results\//,
	/(^|\/)\.jscpd\//,
	/(^|\/)\.ruff_cache\//,
	/(^|\/)\.pytest_cache\//,
	/(^|\/)__pycache__\//,
	/(^|\/)\.eslintcache$/,
	/(^|\/)\.DS_Store$/,
	/\.pyc$/,
	/\.log$/,
	/\.orig$/,
	/\.rej$/,
	/\.bak$/
];
const FORBIDDEN_TEXT = [
	{ pattern: /\btodo\b/i, message: "TODO markers must be linked to an issue before landing" },
	{ pattern: /\bfixme\b/i, message: "FIXME markers must be linked to an issue before landing" },
	{ pattern: /\bxxx\b/i, message: "XXX markers are not allowed in committed code" },
	{ pattern: /\bhack\b/i, message: "HACK markers are not allowed in committed code" },
	{ pattern: /lorem ipsum/i, message: "placeholder lorem ipsum copy is not allowed" },
	{ pattern: /\bas an ai\b/i, message: "AI-disclosure filler text is not product copy" },
	{ pattern: /\bchatgpt\b/i, message: "AI tool residue must not be committed" },
	{ pattern: /\bcopilot\b/i, message: "AI tool residue must not be committed" },
	{ pattern: /generated by ai/i, message: "AI-generation residue must not be committed" }
];
const FORBIDDEN_CODE = [
	{ pattern: /\bdebugger\b/, message: "debugger statements are not allowed" },
	{
		pattern: /\bconsole\.(log|debug|trace|warn|error)\s*\(/,
		message: "console logging is not allowed in shipped code"
	},
	{ pattern: /\balert\s*\(/, message: "blocking alert() calls are not allowed; use inline UI state" }
];

const root = repoRoot();
process.chdir(root);
mkdirSync(QUALITY_DIR, { recursive: true });

const failures = [];
const checks = [];
const startedAt = Date.now();
const files = gitFiles();

function repoRoot() {
	const out = spawnSync("git", ["rev-parse", "--show-toplevel"], { encoding: "utf8" });
	if (out.status !== 0) {
		console.error("quality: not inside a git checkout");
		process.exit(2);
	}
	return out.stdout.trim();
}

function gitFiles() {
	const out = spawnSync("git", ["ls-files", "--cached", "--others", "--exclude-standard", "-z"], {
		encoding: "utf8"
	});
	if (out.status !== 0) throw new Error(out.stderr || "git ls-files failed");
	return out.stdout
		.split("\0")
		.filter(Boolean)
		.filter((file) => existsSync(file) && statSync(file).isFile())
		.sort();
}

function fail(check, file, line, message) {
	failures.push({ check, file: file || null, line: line || null, message });
}

function read(file) {
	return readFileSync(file, "utf8");
}

function rel(file) {
	return file.split(path.sep).join("/");
}

function ext(file) {
	return path.extname(file);
}

function sourceFiles() {
	return files.filter((file) => SOURCE_EXTS.has(ext(file)));
}

function lineNumber(text, offset) {
	return text.slice(0, offset).split("\n").length;
}

function fileLineEntries(file, text) {
	return text.split(/\r?\n/).map((line, index) => ({ line, number: index + 1, file }));
}

function runCheck(name, fn) {
	const start = Date.now();
	const before = failures.length;
	try {
		fn(name);
	} catch (error) {
		fail(name, null, null, error && error.stack ? error.stack : String(error));
	}
	checks.push({ name, durationMs: Date.now() - start, failures: failures.length - before });
}

function command(check, cmd, args) {
	const out = spawnSync(cmd, args, { encoding: "utf8", cwd: root });
	if (out.status !== 0) {
		const output = [out.stdout, out.stderr].filter(Boolean).join("\n").trim();
		fail(check, args[args.length - 1], null, output || `${cmd} failed`);
	}
}

function commandWithEnv(cmd, args, env, opts = {}) {
	return spawnSync(cmd, args, {
		encoding: "utf8",
		cwd: root,
		env: { ...process.env, ...env },
		maxBuffer: opts.maxBuffer || 1024 * 1024,
		timeout: opts.timeout || 0
	});
}

function bin(name) {
	return path.join("node_modules", ".bin", name);
}

function pyBin(name) {
	return path.join(".quality", "python", "bin", name);
}

function requireFile(check, file, hint) {
	if (!existsSync(file)) fail(check, file, null, hint);
}

function stableJson(value) {
	return `${JSON.stringify(value, null, "\t")}\n`;
}

function formattedSnapshot(file, value) {
	const raw = stableJson(value);
	if (!existsSync(bin("prettier"))) return raw;
	const out = spawnSync(bin("prettier"), ["--stdin-filepath", file], {
		cwd: root,
		encoding: "utf8",
		input: raw
	});
	return out.status === 0 ? out.stdout : raw;
}

function readJson(file) {
	return JSON.parse(read(file));
}

function updateOrCompareSnapshot(check, file, actual, label) {
	const text = formattedSnapshot(file, actual);
	if (UPDATE_CONTRACTS) {
		mkdirSync(path.dirname(file), { recursive: true });
		writeFileSync(file, text);
		return;
	}
	if (!existsSync(file)) {
		fail(check, file, null, `${label} snapshot is missing; run npm run contracts:update`);
		return;
	}
	const expected = read(file);
	if (expected !== text) {
		fail(check, file, null, `${label} changed; review the diff and run npm run contracts:update if intentional`);
	}
}

runCheck("toolchain", (check) => {
	const major = Number(process.versions.node.split(".")[0]);
	if (major < 20) fail(check, null, null, `Node >= 20 is required; found ${process.version}`);
	if (spawnSync("git", ["--version"], { encoding: "utf8" }).status !== 0) fail(check, null, null, "git is required");
});

runCheck("repository hygiene", (check) => {
	for (const file of files) {
		const name = rel(file);
		for (const pattern of GENERATED_PATTERNS) {
			if (pattern.test(name)) {
				fail(check, file, null, "generated, cache, editor, or backup artifact is not allowed");
			}
		}
	}
	for (const required of ["public_html/index.html", "public_html/main.js", "proxy/app.py", "tools/deploy.sh"]) {
		if (!existsSync(required)) fail(check, required, null, "required project entrypoint is missing");
	}
});

runCheck("license headers", (check) => {
	for (const file of files) {
		const name = rel(file);
		if (!(/^(public_html|proxy|tools|tests)\//.test(name) && [".js", ".mjs", ".py", ".sh"].includes(ext(file)))) {
			continue;
		}
		const header = read(file).split(/\r?\n/).slice(0, 3).join("\n");
		if (!header.includes("SPDX-License-Identifier: GPL-3.0-or-later")) {
			fail(check, file, 1, "source files must declare the GPL-3.0-or-later SPDX header");
		}
	}
});

runCheck("syntax", (check) => {
	for (const file of files.filter((item) => JS_EXTS.has(ext(item)))) {
		command(check, process.execPath, ["--check", file]);
	}
	const pythonFiles = files.filter((item) => ext(item) === ".py");
	if (pythonFiles.length > 0) {
		const py = spawnSync("python3", ["--version"], { encoding: "utf8" });
		if (py.status === 0) for (const file of pythonFiles) command(check, "python3", ["-m", "py_compile", file]);
		else fail(check, null, null, "python3 is required for proxy syntax checks");
	}
	for (const file of files.filter((item) => ext(item) === ".json")) {
		try {
			JSON.parse(read(file));
		} catch (error) {
			fail(check, file, null, `invalid JSON: ${error.message}`);
		}
	}
});

runCheck("prettier", (check) => {
	requireFile(check, bin("prettier"), "run npm ci before pushing");
	if (existsSync(bin("prettier"))) command(check, bin("prettier"), ["--check", "."]);
});

runCheck("eslint", (check) => {
	requireFile(check, bin("eslint"), "run npm ci before pushing");
	if (existsSync(bin("eslint"))) command(check, bin("eslint"), [".", "--max-warnings", "0"]);
});

runCheck("stylelint", (check) => {
	requireFile(check, bin("stylelint"), "run npm ci before pushing");
	if (existsSync(bin("stylelint"))) command(check, bin("stylelint"), ["public_html/styles/**/*.css"]);
});

runCheck("knip", (check) => {
	requireFile(check, bin("knip"), "run npm ci before pushing");
	if (existsSync(bin("knip"))) command(check, bin("knip"), ["--production"]);
});

runCheck("jscpd", (check) => {
	requireFile(check, bin("jscpd"), "run npm ci before pushing");
	if (existsSync(bin("jscpd"))) command(check, bin("jscpd"), ["--config", ".jscpd.json"]);
});

runCheck("npm audit", (check) => {
	requireFile(check, "package-lock.json", "package-lock.json is required for npm audit");
	if (existsSync("package-lock.json")) command(check, "npm", ["audit", "--audit-level=moderate"]);
});

function directDependencies(pkg) {
	const sections = ["dependencies", "devDependencies", "optionalDependencies"];
	return sections
		.flatMap((section) => (pkg[section] ? Object.entries(pkg[section]) : []))
		.sort(([a], [b]) => a.localeCompare(b));
}

function npmViewJson(args) {
	const out = spawnSync("npm", ["view", ...args, "--json"], { encoding: "utf8", cwd: root });
	if (out.status !== 0) throw new Error([out.stdout, out.stderr].filter(Boolean).join("\n").trim());
	const text = out.stdout.trim();
	return text ? JSON.parse(text) : null;
}

runCheck("dependency policy", (check) => {
	const exactVersion = /^\d+\.\d+\.\d+(?:-[\d.A-Za-z-]+)?$/;
	requireFile(check, "package.json", "package.json is required");
	requireFile(check, "package-lock.json", "package-lock.json is required");
	if (!existsSync("package.json") || !existsSync("package-lock.json")) return;

	const pkg = readJson("package.json");
	const lock = readJson("package-lock.json");
	const rootPackage = lock.packages && lock.packages[""];
	if (!rootPackage) {
		fail(check, "package-lock.json", null, "lockfile root package metadata is missing");
		return;
	}

	for (const [name, version] of directDependencies(pkg)) {
		if (!exactVersion.test(version)) {
			fail(check, "package.json", null, `${name} must use an exact pinned version; found ${version}`);
		}
		const lockedSpec =
			(rootPackage.dependencies && rootPackage.dependencies[name]) ||
			(rootPackage.devDependencies && rootPackage.devDependencies[name]) ||
			(rootPackage.optionalDependencies && rootPackage.optionalDependencies[name]);
		if (lockedSpec !== version) {
			fail(
				check,
				"package-lock.json",
				null,
				`${name} lockfile spec ${lockedSpec || "<missing>"} must equal ${version}`
			);
		}
		const lockedPackage = lock.packages[`node_modules/${name}`];
		if (!lockedPackage || lockedPackage.version !== version) {
			fail(
				check,
				"package-lock.json",
				null,
				`${name} resolved version ${lockedPackage && lockedPackage.version ? lockedPackage.version : "<missing>"} must equal ${version}`
			);
		}
	}

	for (const [location, meta] of Object.entries(lock.packages || {})) {
		if (meta && meta.deprecated) {
			fail(check, "package-lock.json", null, `${location || "<root>"} is deprecated: ${meta.deprecated}`);
		}
	}

	for (const [name, version] of directDependencies(pkg)) {
		let deprecated;
		let time;
		try {
			deprecated = npmViewJson([`${name}@${version}`, "deprecated"]);
			time = npmViewJson([name, "time"]);
		} catch (error) {
			fail(check, "package.json", null, `could not read npm metadata for ${name}: ${error.message}`);
			continue;
		}
		if (deprecated) fail(check, "package.json", null, `${name}@${version} is deprecated: ${deprecated}`);
		const modifiedAt = time && time.modified ? Date.parse(time.modified) : Number.NaN;
		const versionPublishedAt = time && time[version] ? Date.parse(time[version]) : Number.NaN;
		if (!Number.isFinite(modifiedAt) || !Number.isFinite(versionPublishedAt)) {
			fail(check, "package.json", null, `${name} is missing registry release timestamps`);
			continue;
		}
		const ageDays = Math.floor((Date.now() - modifiedAt) / 86400000);
		if (ageDays > MAX_DIRECT_DEPENDENCY_RELEASE_AGE_DAYS) {
			fail(
				check,
				"package.json",
				null,
				`${name} has no release in ${ageDays} days; limit is ${MAX_DIRECT_DEPENDENCY_RELEASE_AGE_DAYS}`
			);
		}
	}
});

runCheck("ruff", (check) => {
	requireFile(check, pyBin("ruff"), "run tools/install-hooks.sh before pushing");
	if (existsSync(pyBin("ruff"))) {
		command(check, pyBin("ruff"), ["check", "proxy"]);
		command(check, pyBin("ruff"), ["format", "--check", "proxy"]);
	}
});

runCheck("pip audit", (check) => {
	requireFile(check, pyBin("pip-audit"), "run tools/install-hooks.sh before pushing");
	if (existsSync(pyBin("pip-audit"))) {
		command(check, pyBin("pip-audit"), ["-r", "proxy/requirements.txt", "--strict"]);
	}
});

function unitTestFiles() {
	return files
		.filter((file) => rel(file).startsWith("tests/unit/") && file.endsWith(".test.mjs"))
		.map((file) => rel(file));
}

runCheck("unit tests", (check) => {
	const tests = unitTestFiles();
	if (tests.length === 0) {
		fail(check, "tests/unit", null, "unit tests are required for mutation testing");
		return;
	}
	command(check, process.execPath, ["--test", ...tests]);
});

runCheck("playwright axe smoke", (check) => {
	requireFile(check, bin("playwright"), "run npm ci and npx playwright install chromium before pushing");
	if (existsSync(bin("playwright"))) command(check, bin("playwright"), ["test"]);
});

runCheck("text hygiene", (check) => {
	for (const file of sourceFiles()) {
		const name = rel(file);
		const scanForbiddenText = name !== "tools/quality.mjs";
		const scanForbiddenCode = name.startsWith("public_html/") && CODE_EXTS.has(ext(file));
		const text = read(file);
		for (const entry of fileLineEntries(file, text)) {
			if (/^(<<<<<<<|=======|>>>>>>>)($| )/.test(entry.line)) {
				fail(check, file, entry.number, "merge conflict marker is not allowed");
			}
			if (scanForbiddenText) {
				for (const rule of FORBIDDEN_TEXT) {
					if (rule.pattern.test(entry.line)) fail(check, file, entry.number, rule.message);
				}
			}
			if (scanForbiddenCode) {
				for (const rule of FORBIDDEN_CODE) {
					if (rule.pattern.test(entry.line)) fail(check, file, entry.number, rule.message);
				}
			}
			const limit = TEXT_LINE_LIMITS.get(ext(file));
			if (limit && entry.line.length > limit) {
				fail(check, file, entry.number, `line is ${entry.line.length} chars; limit is ${limit}`);
			}
		}
	}
});

function importsFor(file) {
	const text = read(file);
	const imports = [];
	const regex = /(?:^|\n)(\s*import\s+([\S\s]*?)\s+from\s+["']([^"']+)["'];)/g;
	let match;
	while ((match = regex.exec(text))) {
		const index = match.index + (match[0].startsWith("\n") ? 1 : 0);
		imports.push({ spec: match[3], index, line: lineNumber(text, index) });
	}
	return imports;
}

function resolveImport(file, spec) {
	return rel(path.normalize(path.join(path.dirname(file), spec)));
}

function layerOf(file) {
	const name = rel(file);
	if (name === "public_html/main.js") return { layer: 5, label: "app" };
	if (name.startsWith("public_html/views/")) return { layer: 4, label: "views" };
	if (name.startsWith("public_html/lib/organisms/")) return { layer: 3, label: "organisms" };
	if (name.startsWith("public_html/lib/molecules/")) return { layer: 2, label: "molecules" };
	if (name.startsWith("public_html/lib/atoms/")) return { layer: 1, label: "atoms" };
	if (name.startsWith("public_html/lib/core/")) return { layer: 0, label: "core" };
	return { layer: -1, label: "other" };
}

function importAllowed(source, target) {
	const s = layerOf(source);
	const t = layerOf(target);
	if (s.layer === -1 || t.layer === -1) return true;
	if (source === "public_html/main.js") return true;
	if (source === "public_html/views/router.js" && target.startsWith("public_html/views/")) return true;
	return t.layer <= s.layer;
}

runCheck("imports and architecture", (check) => {
	const graph = new Map();
	const browserFiles = files.filter((item) => JS_EXTS.has(ext(item)) && rel(item).startsWith("public_html/"));
	for (const file of browserFiles) {
		const seen = new Set();
		const deps = [];
		for (const item of importsFor(file)) {
			if (seen.has(item.spec)) fail(check, file, item.line, `duplicate import from ${item.spec}`);
			seen.add(item.spec);
			if (!item.spec.startsWith(".")) {
				fail(check, file, item.line, `browser modules must use local relative imports; found ${item.spec}`);
				continue;
			}
			if (!item.spec.endsWith(".js")) {
				fail(check, file, item.line, `local imports must include the .js extension: ${item.spec}`);
			}
			const target = resolveImport(file, item.spec);
			if (!existsSync(target)) {
				fail(check, file, item.line, `import target does not exist: ${item.spec}`);
				continue;
			}
			if (target === rel(file)) fail(check, file, item.line, "self-import is not allowed");
			if (!importAllowed(rel(file), target)) {
				fail(
					check,
					file,
					item.line,
					`${layerOf(file).label} layer must not import upward from ${layerOf(target).label}`
				);
			}
			deps.push(target);
		}
		graph.set(rel(file), deps);
	}
	const visiting = new Set();
	const visited = new Set();
	const stack = [];
	function dfs(node) {
		if (visiting.has(node)) {
			fail(
				check,
				node,
				null,
				`circular import detected: ${[...stack.slice(stack.indexOf(node)), node].join(" -> ")}`
			);
			return;
		}
		if (visited.has(node)) return;
		visiting.add(node);
		stack.push(node);
		for (const dep of graph.get(node) || []) dfs(dep);
		stack.pop();
		visiting.delete(node);
		visited.add(node);
	}
	for (const node of graph.keys()) dfs(node);
});

function exportedNames(file) {
	const text = read(file);
	const names = new Set();
	for (const match of text.matchAll(/export\s+(?:async\s+)?function\s+([$A-Z_a-z][\w$]*)/g)) names.add(match[1]);
	for (const match of text.matchAll(/export\s+(?:const|let|var)\s+([$A-Z_a-z][\w$]*)/g)) names.add(match[1]);
	for (const match of text.matchAll(/export\s*{\s*([^}]+)\s*}/g)) {
		for (const raw of match[1].split(",")) {
			const exported = raw
				.trim()
				.split(/\s+as\s+/)
				.pop()
				.trim();
			if (exported) names.add(exported);
		}
	}
	return [...names].sort();
}

function matchingBraceEnd(text, start) {
	let depth = 0;
	let quote = "";
	let lineComment = false;
	let blockComment = false;
	let escaped = false;
	for (let index = start; index < text.length; index += 1) {
		const char = text[index];
		const next = text[index + 1];
		if (lineComment) {
			if (char === "\n") lineComment = false;
			continue;
		}
		if (blockComment) {
			if (char === "*" && next === "/") {
				blockComment = false;
				index += 1;
			}
			continue;
		}
		if (quote) {
			if (escaped) {
				escaped = false;
			} else if (char === "\\") {
				escaped = true;
			} else if (char === quote) {
				quote = "";
			}
			continue;
		}
		if (char === "/" && next === "/") {
			lineComment = true;
			index += 1;
			continue;
		}
		if (char === "/" && next === "*") {
			blockComment = true;
			index += 1;
			continue;
		}
		if (char === '"' || char === "'" || char === "`") {
			quote = char;
			continue;
		}
		if (char === "{") {
			depth += 1;
		} else if (char === "}") {
			depth -= 1;
			if (depth === 0) return index;
		}
	}
	return -1;
}

function extractObjectBody(text, marker) {
	const markerIndex = text.indexOf(marker);
	if (markerIndex === -1) return "";
	const start = text.indexOf("{", markerIndex);
	if (start === -1) return "";
	const end = matchingBraceEnd(text, start);
	return end === -1 ? "" : text.slice(start + 1, end);
}

function quotedKeyAt(body, index, quoteChar) {
	let end = index + 1;
	while (end < body.length) {
		if (body[end] === "\\" && end + 1 < body.length) {
			end += 2;
			continue;
		}
		if (body[end] === quoteChar) break;
		end += 1;
	}
	if (end >= body.length) return null;
	return { key: body.slice(index + 1, end), index: end };
}

function identifierKeyAt(body, index) {
	const match = /^[$A-Z_a-z][\w$-]*/.exec(body.slice(index));
	return match ? { key: match[0], index: index + match[0].length - 1 } : null;
}

function objectKeyAt(body, index) {
	const char = body[index];
	if (char === '"' || char === "'") return quotedKeyAt(body, index, char);
	return /[$A-Z_a-z]/.test(char) ? identifierKeyAt(body, index) : null;
}

function hasColonAfterKey(body, index) {
	let probe = index + 1;
	while (/\s/.test(body[probe] || "")) probe += 1;
	return body[probe] === ":";
}

function topLevelObjectKeys(body) {
	const keys = [];
	let depth = 0;
	let quote = "";
	let escaped = false;
	for (let index = 0; index < body.length; index += 1) {
		const char = body[index];
		if (quote) {
			if (escaped) escaped = false;
			else if (char === "\\") escaped = true;
			else if (char === quote) quote = "";
			continue;
		}

		if (depth === 0) {
			const candidate = objectKeyAt(body, index);
			if (candidate && hasColonAfterKey(body, candidate.index)) {
				keys.push(candidate.key);
				index = candidate.index;
				continue;
			}
		}

		if (char === '"' || char === "'" || char === "`") {
			quote = char;
			continue;
		}
		if (char === "{" || char === "(" || char === "[") depth += 1;
		else if (char === "}" || char === ")" || char === "]") depth = Math.max(0, depth - 1);
	}
	return [...new Set(keys)].sort();
}

function objectKeysFromConst(file, name) {
	const text = read(file);
	return [
		...topLevelObjectKeys(extractObjectBody(text, `const ${name} =`)),
		...topLevelObjectKeys(extractObjectBody(text, `export const ${name} =`))
	];
}

function publicRoutes() {
	const routeKeys = objectKeysFromConst("public_html/views/router.js", "ROUTES").map((key) => `/${key}`);
	const staticKeys = objectKeysFromConst("public_html/views/static.js", "STATIC").map((key) => `/${key}`);
	const patterns = [
		"/",
		"/search",
		"/by/:name",
		"/tools/create",
		"/tools/:name",
		"/tools/:name/edit",
		"/tools/:name/edit-annotations",
		"/tools/:name/history",
		"/tools/:name/history/:revision",
		"/lists/create",
		"/lists/:id",
		"/lists/:id/edit",
		"/lists/:id/history"
	];
	return [...new Set([...patterns, ...routeKeys, ...staticKeys])].sort();
}

function schemaShapes() {
	const apiText = read("public_html/lib/core/api.js");
	const normalizedTool = [
		...topLevelObjectKeys(extractObjectBody(apiText, "const o =")),
		"status",
		"weeklyViews"
	].sort();
	const normalizedList = topLevelObjectKeys(extractObjectBody(apiText, "return"));
	return {
		normalizeList: normalizedList,
		normalizeTool: [...new Set(normalizedTool)].sort()
	};
}

function publicApiContract() {
	const exports = {};
	for (const file of files.filter((item) => JS_EXTS.has(ext(item)) && rel(item).startsWith("public_html/"))) {
		const names = exportedNames(file);
		if (names.length > 0) exports[rel(file)] = names;
	}
	return {
		exports,
		routes: publicRoutes(),
		schemas: schemaShapes()
	};
}

runCheck("public API contract", (check) => {
	updateOrCompareSnapshot(check, API_CONTRACT_PATH, publicApiContract(), "public API contract");
});

runCheck("links and route safety", (check) => {
	for (const file of files.filter((item) => [".js", ".html"].includes(ext(item)))) {
		const text = read(file);
		for (const entry of fileLineEntries(file, text)) {
			if (entry.line.includes("/#/")) fail(check, file, entry.number, "hash-router URLs are not allowed");
			if (/href=["']#["']/.test(entry.line)) {
				fail(check, file, entry.number, 'dead href="#" links are not allowed');
			}
			if (/href=["'][^"']+\.html["#'?]/.test(entry.line)) {
				fail(check, file, entry.number, "local links must use app routes, not .html files");
			}
		}
		for (const match of text.matchAll(/<a\b[\S\s]*?>/g)) {
			const tag = match[0];
			if (!/\btarget\s*=\s*["']_blank["']/.test(tag) || tag.includes("EXTERNAL_REL")) continue;
			const rel = tag.match(/\brel\s*=\s*(["'])(.*?)\1/);
			const relTokens = new Set((rel ? rel[2] : "").split(/\s+/).filter(Boolean));
			if (!relTokens.has("noopener") || !relTokens.has("nofollow")) {
				fail(
					check,
					file,
					lineNumber(text, match.index),
					'target="_blank" must include rel="noopener nofollow"'
				);
			}
		}
		for (const tag of text.match(/<img\b[^>]*>/g) || []) {
			if (!/\balt=/.test(tag)) {
				fail(check, file, lineNumber(text, text.indexOf(tag)), "img tags must include alt text");
			}
		}
	}
});

function cssWithoutComments(file) {
	return read(file).replaceAll(/\/\*[\S\s]*?\*\//g, "");
}

function designTokens() {
	const tokens = new Set();
	const colorValues = new Set();
	if (!existsSync(DESIGN_TOKEN_FILE)) return { tokens, colorValues };
	const text = cssWithoutComments(DESIGN_TOKEN_FILE);
	const definitionRegex = /(--[\w-]+)\s*:\s*([^;]+);/g;
	let match;
	while ((match = definitionRegex.exec(text))) {
		tokens.add(match[1]);
		for (const color of match[2].match(/#[\dA-Fa-f]{3,8}\b/g) || []) colorValues.add(color.toLowerCase());
	}
	return { tokens, colorValues };
}

function styleLinkOrder() {
	const html = read("public_html/index.html");
	return [...html.matchAll(/<link\b[^>]*href=["']([^"']+\.css)["'][^>]*>/g)].map((match) =>
		match[1].replace(/^\.\//, "")
	);
}

runCheck("design system drift", (check) => {
	const { tokens, colorValues } = designTokens();
	if (tokens.size === 0) fail(check, DESIGN_TOKEN_FILE, null, "design token source is missing or empty");
	const cssOrder = styleLinkOrder();
	if (cssOrder[0] !== "/styles/tokens.css") {
		fail(check, "public_html/index.html", null, "tokens.css must be the first stylesheet loaded");
	}
	for (const required of [
		"--color-surface",
		"--color-text",
		"--space-4",
		"--fs-body",
		"--radius-sm",
		"--focus-ring"
	]) {
		if (!tokens.has(required)) {
			fail(check, DESIGN_TOKEN_FILE, null, `required design token is missing: ${required}`);
		}
	}
	for (const file of files.filter(
		(item) => [".css", ".js", ".html"].includes(ext(item)) && rel(item).startsWith("public_html/")
	)) {
		const name = rel(file);
		const text = ext(file) === ".css" ? cssWithoutComments(file) : read(file);
		let match;
		const varRegex = /var\(\s*(--[\w-]+)/g;
		while ((match = varRegex.exec(text))) {
			const token = match[1];
			if (!tokens.has(token)) fail(check, file, lineNumber(text, match.index), `unknown design token ${token}`);
		}
		const definitionRegex = /(^|[\s;{])(--[\w-]+)\s*:/g;
		while ((match = definitionRegex.exec(text))) {
			const token = match[2];
			if (name !== DESIGN_TOKEN_FILE && !tokens.has(token)) {
				fail(
					check,
					file,
					lineNumber(text, match.index),
					`custom property ${token} must be registered in ${DESIGN_TOKEN_FILE}`
				);
			}
		}
		const colorRegex = /#[\dA-Fa-f]{3,8}\b|rgba?\([^)]+\)|hsla?\([^)]+\)/g;
		while ((match = colorRegex.exec(text))) {
			const literal = match[0].toLowerCase();
			if (name === DESIGN_TOKEN_FILE) continue;
			if (ext(file) === ".css") {
				fail(check, file, lineNumber(text, match.index), `raw colour ${literal} must be a design token`);
			} else if (!colorValues.has(literal)) {
				fail(
					check,
					file,
					lineNumber(text, match.index),
					`raw colour ${literal} is not registered in design tokens`
				);
			}
		}
	}
});

function splitSelectors(raw) {
	const selectors = [];
	let current = "";
	let depth = 0;
	let quote = "";
	for (const char of raw) {
		if (quote) {
			current += char;
			if (char === quote) quote = "";
			continue;
		}
		if (char === '"' || char === "'") {
			quote = char;
			current += char;
			continue;
		}
		if (char === "(" || char === "[") depth += 1;
		else if (char === ")" || char === "]") depth = Math.max(0, depth - 1);
		if (char === "," && depth === 0) {
			selectors.push(current.trim());
			current = "";
		} else {
			current += char;
		}
	}
	if (current.trim()) selectors.push(current.trim());
	return selectors;
}

runCheck("CSS selectors", (check) => {
	for (const file of files.filter((item) => ext(item) === ".css")) {
		const text = cssWithoutComments(file);
		const seen = new Map();
		const regex = /([^{}]+){([^{}]*)}/g;
		let match;
		while ((match = regex.exec(text))) {
			const raw = match[1].trim();
			if (!raw || raw.startsWith("@") || raw === "from" || raw === "to" || raw.endsWith("%")) continue;
			const body = match[2].trim().replaceAll(/\s+/g, " ");
			if (!body) continue;
			for (const selector of splitSelectors(raw).filter(Boolean)) {
				const key = `${selector} { ${body} }`;
				const first = seen.get(key);
				const line = lineNumber(text, match.index);
				if (first) {
					fail(check, file, line, `duplicate selector/body "${selector}" first appeared on line ${first}`);
				} else {
					seen.set(key, line);
				}
			}
		}
	}
});

function escapeRegex(value) {
	return value.replaceAll(/[$()*+.?[\\\]^{|}]/g, "\\$&");
}

function identifierOccurrences(text, name) {
	return [...text.matchAll(new RegExp(`(?<![A-Za-z0-9_$])${escapeRegex(name)}(?![A-Za-z0-9_$])`, "g"))].length;
}

function browserModuleGraph() {
	const browserFiles = files
		.filter((item) => JS_EXTS.has(ext(item)) && rel(item).startsWith("public_html/"))
		.map((file) => rel(file));
	const graph = new Map(browserFiles.map((file) => [file, []]));
	for (const file of browserFiles) {
		for (const item of importsFor(file)) {
			if (!item.spec.startsWith(".")) continue;
			const target = resolveImport(file, item.spec);
			if (graph.has(target)) graph.get(file).push(target);
		}
	}
	return graph;
}

function jsModuleGraph() {
	const moduleFiles = files.filter((item) => JS_EXTS.has(ext(item))).map((file) => rel(file));
	const graph = new Map(moduleFiles.map((file) => [file, []]));
	for (const file of moduleFiles) {
		for (const item of importsFor(file)) {
			if (!item.spec.startsWith(".")) continue;
			const target = resolveImport(file, item.spec);
			if (graph.has(target)) graph.get(file).push(target);
		}
	}
	return graph;
}

function importDepthFor(file, graph, seen = new Set()) {
	if (seen.has(file)) return 0;
	const deps = graph.get(file) || [];
	if (deps.length === 0) return graph.has(file) ? 1 : 0;
	const nextSeen = new Set(seen);
	nextSeen.add(file);
	return 1 + Math.max(...deps.map((dep) => importDepthFor(dep, graph, nextSeen)));
}

function codeModuleFiles() {
	return files.filter((file) => CODE_EXTS.has(ext(file))).map((file) => rel(file));
}

function moduleCyclomatic(text) {
	return 1 + (text.match(/\b(if|for|while|case|catch)\b|\?|&&|\|\|/g) || []).length;
}

function moduleCognitive(text) {
	let score = 0;
	let nesting = 0;
	for (const line of text.split(/\r?\n/)) {
		const trimmed = line.trim();
		if (/^[)\]}]/.test(trimmed)) nesting = Math.max(0, nesting - 1);
		const controls = trimmed.match(/\b(if|for|while|case|catch|switch)\b|\?|&&|\|\|/g) || [];
		score += controls.length * (1 + nesting);
		const opens = (trimmed.match(/[([{]/g) || []).length;
		const closes = (trimmed.match(/[)\]}]/g) || []).length;
		nesting = Math.max(0, nesting + opens - closes);
	}
	return score;
}

function moduleMetrics() {
	const graph = jsModuleGraph();
	const fanIn = new Map([...graph.keys()].map((file) => [file, 0]));
	for (const deps of graph.values()) {
		for (const dep of deps) fanIn.set(dep, (fanIn.get(dep) || 0) + 1);
	}
	const modules = {};
	for (const file of codeModuleFiles()) {
		const text = read(file);
		modules[file] = {
			lines: text.split(/\r?\n/).length,
			cyclomatic: moduleCyclomatic(text),
			cognitive: moduleCognitive(text),
			fanIn: fanIn.get(file) || 0,
			fanOut: (graph.get(file) || []).length,
			importDepth: importDepthFor(file, graph)
		};
	}
	return { defaults: MODULE_DEFAULT_LIMITS, modules };
}

function defaultModuleBudget(file) {
	const extension = ext(file);
	return {
		lines: MODULE_DEFAULT_LIMITS.lines[extension] || 120,
		cyclomatic: MODULE_DEFAULT_LIMITS.branches[extension] || 20,
		cognitive: (MODULE_DEFAULT_LIMITS.branches[extension] || 20) * 2,
		fanIn: MODULE_DEFAULT_LIMITS.fanIn,
		fanOut: MODULE_DEFAULT_LIMITS.fanOut,
		importDepth: MODULE_DEFAULT_LIMITS.importDepth
	};
}

runCheck("module complexity budgets", (check) => {
	const actual = moduleMetrics();
	if (UPDATE_CONTRACTS) {
		updateOrCompareSnapshot(check, MODULE_BUDGET_PATH, actual, "module budgets");
		return;
	}
	if (!existsSync(MODULE_BUDGET_PATH)) {
		fail(check, MODULE_BUDGET_PATH, null, "module budget snapshot is missing; run npm run contracts:update");
		return;
	}
	const expected = readJson(MODULE_BUDGET_PATH);
	for (const file of Object.keys(expected.modules || {})) {
		if (!actual.modules[file]) {
			fail(check, MODULE_BUDGET_PATH, null, `${file} was deleted; update module budget snapshot`);
		}
	}
	for (const [file, metrics] of Object.entries(actual.modules)) {
		const budget = (expected.modules && expected.modules[file]) || defaultModuleBudget(file);
		for (const [metric, value] of Object.entries(metrics)) {
			if (value > budget[metric]) {
				fail(check, file, null, `${metric} is ${value}; budget is ${budget[metric]}`);
			}
		}
	}
});

function reachableModules(graph, entry) {
	const seen = new Set();
	function visit(node) {
		if (seen.has(node) || !graph.has(node)) return;
		seen.add(node);
		for (const dep of graph.get(node)) visit(dep);
	}
	visit(entry);
	return seen;
}

function classNamesInSource() {
	const names = new Set();
	for (const file of files.filter(
		(item) => [".js", ".html"].includes(ext(item)) && rel(item).startsWith("public_html/")
	)) {
		for (const match of read(file).matchAll(/[A-Za-z][\w-]*(?:__[A-Za-z][\w-]*)?(?:--[A-Za-z][\w-]*)?/g)) {
			names.add(match[0]);
		}
	}
	return names;
}

runCheck("dead code", (check) => {
	const graph = browserModuleGraph();
	const reachable = reachableModules(graph, APP_ENTRY);
	for (const file of graph.keys()) {
		if (!reachable.has(file)) fail(check, file, null, "browser module is not reachable from public_html/main.js");
	}
	const referencedClasses = classNamesInSource();
	for (const file of files.filter((item) => ext(item) === ".css" && rel(item).startsWith("public_html/styles/"))) {
		const text = cssWithoutComments(file);
		for (const match of text.matchAll(/\.([A-Za-z][\w-]*)/g)) {
			const name = match[1];
			if (name.startsWith("is-") || name.startsWith("has-") || name.startsWith("on-")) continue;
			if (!referencedClasses.has(name)) {
				fail(
					check,
					file,
					lineNumber(text, match.index),
					`CSS class .${name} is not referenced outside stylesheets`
				);
			}
		}
	}
	for (const file of files.filter((item) => JS_EXTS.has(ext(item)) && rel(item).startsWith("public_html/"))) {
		const text = read(file);
		for (const match of text.matchAll(/export\s+function\s+([$A-Z_a-z][\w$]*)/g)) {
			const name = match[1];
			if (identifierOccurrences(text, name) === 1) {
				let imported = false;
				for (const other of files.filter((item) => JS_EXTS.has(ext(item)) && item !== file)) {
					if (read(other).includes(name)) {
						imported = true;
						break;
					}
				}
				if (!imported) {
					fail(check, file, lineNumber(text, match.index), `exported function ${name} appears unused`);
				}
			}
		}
	}
});

function normalizeDuplicateLine(line) {
	return line
		.trim()
		.replaceAll(/(["'`])(?:\\.|(?!\1).)*\1/g, '""')
		.replaceAll(/\b\d+(?:\.\d+)?\b/g, "0")
		.replaceAll(/\s+/g, " ");
}

runCheck("duplicate blocks", (check) => {
	const seen = new Map();
	for (const file of files.filter((item) => [".js", ".mjs", ".css", ".html"].includes(ext(item)))) {
		const normalized = read(file)
			.split(/\r?\n/)
			.map((line) => normalizeDuplicateLine(line));
		for (let index = 0; index <= normalized.length - DUPLICATE_WINDOW; index += 1) {
			const window = normalized.slice(index, index + DUPLICATE_WINDOW);
			if (window.some((line) => !line || line === "}" || line === "};" || line.startsWith("import "))) continue;
			if (window.join("").length < 240) continue;
			const key = window.join("\n");
			const previous = seen.get(key);
			if (previous && (previous.file !== file || previous.line !== index + 1)) {
				fail(
					check,
					file,
					index + 1,
					`duplicate ${DUPLICATE_WINDOW}-line block first appeared in ${previous.file}:${previous.line}`
				);
			} else {
				seen.set(key, { file, line: index + 1 });
			}
		}
	}
});

function functionRanges(text) {
	const ranges = [];
	const regex = /function\s+([$A-Z_a-z][\w$]*)\s*\(([^)]*)\)\s*{/g;
	let match;
	while ((match = regex.exec(text))) {
		const open = text.indexOf("{", match.index);
		const close = matchingBraceEnd(text, open);
		const end = close === -1 ? match.index : close + 1;
		ranges.push({ name: match[1], params: match[2], start: match.index, end });
	}
	return ranges;
}

runCheck("code shape budgets", (check) => {
	for (const file of files.filter((item) => JS_EXTS.has(ext(item)))) {
		const text = read(file);
		for (const fn of functionRanges(text)) {
			const body = text.slice(fn.start, fn.end);
			const lines = body.split(/\r?\n/).length;
			const branches = (body.match(/\b(if|for|while|case|catch|\?|&&|\|\|)\b/g) || []).length;
			const params = fn.params
				.split(",")
				.map((item) => item.trim())
				.filter(Boolean).length;
			if (lines > FUNCTION_LIMITS.lines) {
				fail(check, file, lineNumber(text, fn.start), `${fn.name} has ${lines} lines`);
			}
			if (branches > FUNCTION_LIMITS.branches) {
				fail(check, file, lineNumber(text, fn.start), `${fn.name} has ${branches} branches`);
			}
			if (params > FUNCTION_LIMITS.params) {
				fail(check, file, lineNumber(text, fn.start), `${fn.name} has ${params} parameters`);
			}
		}
	}
});

function normalizeFunctionBody(lines) {
	return lines
		.map((line) => normalizeDuplicateLine(line))
		.filter((line) => line && line !== "}" && line !== "};")
		.join("\n")
		.replaceAll(/\b[$A-Z_a-z][\w$]*\b/g, (word) =>
			[
				"if",
				"else",
				"for",
				"while",
				"return",
				"const",
				"let",
				"var",
				"function",
				"await",
				"async",
				"new"
			].includes(word)
				? word
				: "id"
		);
}

runCheck("duplicate functions", (check) => {
	const seen = new Map();
	for (const file of files.filter((item) => JS_EXTS.has(ext(item)))) {
		const text = read(file);
		for (const fn of functionRanges(text)) {
			const body = normalizeFunctionBody(text.slice(fn.start, fn.end).split(/\r?\n/));
			if (body.length < 240) continue;
			const previous = seen.get(body);
			if (previous) {
				fail(
					check,
					file,
					lineNumber(text, fn.start),
					`${fn.name} duplicates ${previous.file}:${previous.line}`
				);
			} else {
				seen.set(body, { file, line: lineNumber(text, fn.start) });
			}
		}
	}
});

const MUTATION_TARGETS = new Map([
	["public_html/lib/core/api.js", ["firstUrl", "hasValue", "normalizeList", "normalizeTool", "pick", "statusOf"]],
	["public_html/lib/core/dom.js", ["dirAttrs", "esc", "hash", "normalizeVcsUrl", "safeUrl"]],
	["public_html/lib/core/routing.js", ["authorHref", "listHref", "toolHref"]],
	["public_html/lib/core/signals.js", ["completeness", "endorsementOf", "fitsContext", "freshness", "wikiMatches"]],
	[
		"public_html/lib/core/similarity.js",
		["cosine", "idf", "nearestNeighbors", "normalizeVector", "termsOf", "vectorFor"]
	],
	["public_html/lib/core/synth.js", ["synthHealth", "synthSeed", "synthThanks", "synthUsage", "synthViews"]],
	["public_html/lib/core/util.js", ["memoizeAsync", "normStr"]]
]);

const MUTATORS = [
	{ name: "strict equality", pattern: /===/g, replacement: "!==" },
	{ name: "strict inequality", pattern: /!==/g, replacement: "===" },
	{ name: "less-or-equal", pattern: /(?<=\s)<=(?=\s)/g, replacement: "<" },
	{ name: "greater-or-equal", pattern: /(?<=\s)>=(?=\s)/g, replacement: ">" },
	{ name: "less-than", pattern: /(?<=\s)<(?=\s)/g, replacement: "<=" },
	{ name: "greater-than", pattern: /(?<=\s)>(?=\s)/g, replacement: ">=" },
	{ name: "logical and", pattern: /&&/g, replacement: "||" },
	{ name: "logical or", pattern: /\|\|/g, replacement: "&&" },
	{ name: "true literal", pattern: /\btrue\b/g, replacement: "false" },
	{ name: "false literal", pattern: /\bfalse\b/g, replacement: "true" },
	{ name: "math max", pattern: /\bMath\.max\b/g, replacement: "Math.min" },
	{ name: "math min", pattern: /\bMath\.min\b/g, replacement: "Math.max" },
	{ name: "empty string return", pattern: /return ""/g, replacement: "return null" },
	{ name: "null return", pattern: /return null/g, replacement: 'return ""' }
];

function mutationCandidates() {
	const candidates = [];
	for (const [file, names] of MUTATION_TARGETS) {
		if (!existsSync(file)) {
			candidates.push({ missing: true, file, name: "<file>", line: null });
			continue;
		}
		const text = read(file);
		const ranges = functionRanges(text).filter((range) => names.includes(range.name));
		const found = new Set(ranges.map((range) => range.name));
		for (const name of names) {
			if (!found.has(name)) candidates.push({ missing: true, file, name, line: null });
		}
		for (const range of ranges) {
			const body = text.slice(range.start, range.end);
			for (const mutator of MUTATORS) {
				let match;
				while ((match = mutator.pattern.exec(body))) {
					const index = range.start + match.index;
					const candidate = {
						file,
						functionName: range.name,
						line: lineNumber(text, index),
						mutator: mutator.name,
						index,
						from: match[0],
						to: mutator.replacement
					};
					if (!isEquivalentMutation(text, candidate)) candidates.push(candidate);
				}
			}
		}
	}
	return candidates;
}

function isEquivalentMutation(text, mutant) {
	const line = text.split(/\r?\n/)[mutant.line - 1] || "";
	if (
		mutant.file === "public_html/lib/core/dom.js" &&
		mutant.functionName === "safeUrl" &&
		mutant.mutator === "logical or" &&
		line.includes("u === null || u === undefined")
	) {
		return true;
	}
	if (
		mutant.file === "public_html/lib/core/similarity.js" &&
		mutant.functionName === "vectorFor" &&
		mutant.mutator === "logical or" &&
		line.includes("FACET_WEIGHTS[facet] || 1")
	) {
		return true;
	}
	if (
		mutant.file === "public_html/lib/core/similarity.js" &&
		mutant.functionName === "cosine" &&
		mutant.mutator === "less-or-equal" &&
		line.includes("vecA.size <= vecB.size")
	) {
		return true;
	}
	return false;
}

function applyMutation(text, mutant) {
	return text.slice(0, mutant.index) + mutant.to + text.slice(mutant.index + mutant.from.length);
}

function runUnitTestsAgainst(rootDir) {
	return commandWithEnv(
		process.execPath,
		["--max-old-space-size=256", "--test", ...unitTestFiles()],
		{ TOOLHUB_CORE_ROOT: path.resolve(rootDir) },
		{ timeout: 8000 }
	);
}

function runMutant(mutant) {
	const tempRoot = mkdtempSync(path.join(QUALITY_DIR, "mutation-"));
	try {
		cpSync("public_html", path.join(tempRoot, "public_html"), { recursive: true });
		const target = path.join(tempRoot, mutant.file);
		writeFileSync(target, applyMutation(read(mutant.file), mutant));
		const out = runUnitTestsAgainst(tempRoot);
		return {
			killed: out.status !== 0,
			stdout: out.stdout,
			stderr: out.stderr
		};
	} finally {
		rmSync(tempRoot, { recursive: true, force: true });
	}
}

runCheck("mutation testing", (check) => {
	const tests = unitTestFiles();
	if (tests.length === 0) {
		fail(check, "tests/unit", null, "unit tests are required before mutation testing");
		return;
	}
	const baseline = runUnitTestsAgainst(root);
	if (baseline.status !== 0) {
		fail(check, "tests/unit", null, [baseline.stdout, baseline.stderr].filter(Boolean).join("\n").trim());
		return;
	}

	const candidates = mutationCandidates();
	const missing = candidates.filter((candidate) => candidate.missing);
	for (const candidate of missing) {
		fail(check, candidate.file, candidate.line, `mutation target ${candidate.name} was not found`);
	}
	const mutants = candidates.filter((candidate) => !candidate.missing);
	if (mutants.length === 0) {
		fail(check, null, null, "no mutation candidates were generated");
		return;
	}

	const survivors = [];
	let killed = 0;
	for (const mutant of mutants) {
		const result = runMutant(mutant);
		if (result.killed) {
			killed += 1;
		} else {
			survivors.push(mutant);
		}
	}
	const score = (killed / mutants.length) * 100;
	writeFileSync(
		path.join(QUALITY_DIR, "mutation-report.json"),
		stableJson({
			threshold: MUTATION_THRESHOLD,
			score: Number(score.toFixed(2)),
			killed,
			total: mutants.length,
			survivors
		})
	);
	if (score < MUTATION_THRESHOLD) {
		fail(
			check,
			path.join(QUALITY_DIR, "mutation-report.json"),
			null,
			`mutation score ${score.toFixed(2)}% is below ${MUTATION_THRESHOLD}% (${survivors.length} survived)`
		);
		for (const survivor of survivors.slice(0, 10)) {
			fail(
				check,
				survivor.file,
				survivor.line,
				`survived mutant in ${survivor.functionName}: ${survivor.mutator} (${survivor.from} -> ${survivor.to})`
			);
		}
	}
});

const report = {
	startedAt: new Date(startedAt).toISOString(),
	durationMs: Date.now() - startedAt,
	checks,
	failures
};
writeFileSync(REPORT_PATH, `${JSON.stringify(report, null, 2)}\n`);

if (failures.length > 0) {
	console.error(`quality: failed ${failures.length} deterministic gate${failures.length === 1 ? "" : "s"}`);
	for (const failure of failures) {
		const location = [failure.file, failure.line].filter(Boolean).join(":");
		console.error(`- [${failure.check}] ${location} ${failure.message}`);
	}
	console.error(`Full report: ${REPORT_PATH}`);
	process.exit(1);
}

console.log(`quality: ${checks.length} checks passed in ${Date.now() - startedAt}ms`);
