// SPDX-License-Identifier: GPL-3.0-or-later
import assert from "node:assert/strict";
import { test } from "vitest";
import { extractFeatureGroups, renderFeatureDocs } from "../../tools/feature-docs.mjs";

test("extractFeatureGroups reads translated defaults from EXPERIMENTS", () => {
	const code = `
		import { t } from "../lib/core/i18n.js";
		export const EXPERIMENTS = [{
			group: t("g", "Group A"),
			items: [{
				name: t("name", "Feature One"),
				what: t("what", "Does useful work."),
				current: t("current", "Local draft first."),
				need: "POST /api/example/",
				tryHref: "/example",
				tryLabel: t("try", "Try example")
			}]
		}];
	`;
	assert.deepEqual(extractFeatureGroups(code), [
		{
			group: "Group A",
			items: [
				{
					name: "Feature One",
					what: "Does useful work.",
					current: "Local draft first.",
					need: "POST /api/example/",
					tryHref: "/example",
					tryLabel: "Try example"
				}
			]
		}
	]);
});

test("extractFeatureGroups requires complete feature listing records", () => {
	const code = `export const EXPERIMENTS = [{ group: "Group", items: [{ name: "Feature", what: "What", current: "Current" }] }];`;
	assert.throws(() => extractFeatureGroups(code), /missing need/);
});

test("renderFeatureDocs emits a stable markdown table", () => {
	const md = renderFeatureDocs([
		{
			group: "Group - Signals",
			items: [
				{
					name: "Screenshots",
					what: "A preview image strip.",
					current: "Hidden until a real backend data source exists.",
					need: "GET /api/* plus Image storage",
					tryHref: "/features",
					tryLabel: "Feature plan"
				}
			]
		}
	]);
	assert.match(md, /Generated by `npm run features:docs`/);
	assert.match(md, /Total listed features: 1/);
	assert.match(
		md,
		/\| Group - Signals\s+\| Screenshots\s+\| A preview image strip\.\s+\| Hidden until a real backend data source exists\.\s+\| GET \/api\/\\\* plus Image storage\s+\| \[Feature plan\]\(\/features\) \|/
	);
});
