// SPDX-License-Identifier: GPL-3.0-or-later
import assert from "node:assert/strict";
import { test } from "vitest";
import { extractFeatureGroups, renderFeatureDocs } from "../../tools/feature-docs.mjs";

test("extractFeatureGroups reads translated defaults from EXPERIMENTS", () => {
	const code = `
		import { t } from "../lib/core/i18n.js";
		export const EXPERIMENTS = [{
			group: t("g", "Group A"),
			items: [{
				name: t("name", "Feature One"),
				what: t("what", "Does useful work."),
				sim: t("sim", "Local draft first."),
				needs: "POST /api/example/",
				tryHref: "/example",
				tryLabel: t("try", "Try example")
			}]
		}];
	`;
	assert.deepEqual(extractFeatureGroups(code), [
		{
			group: "Group A",
			items: [
				{
					name: "Feature One",
					what: "Does useful work.",
					sim: "Local draft first.",
					needs: "POST /api/example/",
					tryHref: "/example",
					tryLabel: "Try example"
				}
			]
		}
	]);
});

test("extractFeatureGroups requires complete feature listing records", () => {
	const code = `export const EXPERIMENTS = [{ group: "Group", items: [{ name: "Feature", what: "What", sim: "Sim" }] }];`;
	assert.throws(() => extractFeatureGroups(code), /missing needs/);
});

test("renderFeatureDocs emits a stable markdown table", () => {
	const md = renderFeatureDocs([
		{
			group: "Group - Signals",
			items: [
				{
					name: "30-day usage",
					what: 'An "editors used this" figure.',
					sim: "Deterministic per tool.",
					needs: "Usage / view tracking",
					tryHref: "/search?sort=views",
					tryLabel: "Most viewed"
				}
			]
		}
	]);
	assert.match(md, /Generated by `npm run features:docs`/);
	assert.match(md, /Total listed features: 1/);
	assert.match(
		md,
		/\| Group - Signals \| 30-day usage \| An "editors used this" figure\. \| Deterministic per tool\. \| Usage \/ view tracking \| \[Most viewed\]\(\/search\?sort=views\) \|/
	);
});
